#!/usr/bin/env python3
"""Card text for the Spectrum build: the source of truth, plus the emitter.

The rules text on the printed cards is far too long for a 32 column screen in an
8x8 font, so each card is reworded here to the shortest wording that keeps the
rule exact. Text is stored as sentences, not as pre-broken lines, so changing
--width re-wraps everything instead of needing a rewrite.

Only characters the HeroQuest font can actually draw are allowed: A-Z, 0-9,
space and . , ! ' ? = -- everything else in that font's punctuation range is
artwork (monster faces, map tiles), so a stray colon or hyphen would print a
goblin. emit() refuses to write a file that breaks this.

Usage:
    python card_text.py                  # -> card_text.asm at 32 columns
    python card_text.py --width 22       # narrower panel
    python card_text.py --preview        # also render it in the real font
"""

import argparse
import os
import sys
import textwrap

# Hero classes, as bits, so a card can carry who may use it.
BARBARIAN, DWARF, ELF, WIZARD = 1, 2, 4, 8
ALL = BARBARIAN | DWARF | ELF | WIZARD
NOT_WIZARD = ALL & ~WIZARD

FONT = "../../hq-original/gfx8/hq_font_ascii.bin"

# The font draws these and nothing else. Anything outside prints as artwork.
LEGAL = set(" ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,!'?=")

# id, title, body, price in gold (0 = not for sale), who may use it
CARDS = [
    ("restoration", "POTION OF RESTORATION",
     "RESTORES 1 LOST BODY POINT AND 1 LOST MIND POINT.", 300, ALL),
    ("speed", "POTION OF SPEED",
     "ROLL TWICE AS MANY DICE THE NEXT TIME YOU MOVE. DRINK AT ANY TIME.",
     200, ALL),
    ("antidote", "VENOM ANTIDOTE",
     "HEALS UP TO 2 BODY POINTS OF DAMAGE FROM POISON NEEDLES OR DARTS ONLY.",
     300, ALL),
    ("healing", "POTION OF HEALING",
     "RESTORES BODY POINTS EQUAL TO 1 RED DIE, UP TO YOUR STARTING TOTAL. "
     "DRINK AT ANY TIME.", 500, ALL),
    ("dexterity", "POTION OF DEXTERITY",
     "ADDS 5 SQUARES TO YOUR NEXT MOVE, OR MAKES ONE PIT JUMP SUCCEED. "
     "ONE POTION PER TURN.", 100, ALL),
    ("defense", "POTION OF DEFENSE",
     "2 EXTRA COMBAT DICE THE NEXT TIME YOU DEFEND. DRINK AT ANY TIME.",
     0, ALL),
    ("battle", "POTION OF BATTLE",
     "REROLL YOUR ATTACK DICE ONCE.", 200, ALL),
    ("crown", "CROWN OF SHADOWS",
     "ARMOR. 1 EXTRA DEFEND DIE. YOU SEE NORMALLY IN DARKNESS, "
     "MAGICAL AND NOT.", 0, ALL),
    ("acid_oil", "OIL OF ACID IMMUNITY",
     "AVOID ALL ACID DAMAGE FOR ONE QUEST. DISCARD AFTER USE.", 0, ALL),
    ("lightning", "LIGHTNING BOLT",
     "SPELL SCROLL. THE BOLT FLIES STRAIGHT UNTIL IT HITS A WALL OR SHUT DOOR. "
     "2 BODY POINTS TO ALL IN ITS PATH. SCROLL CRUMBLES.", 0, ALL),
    ("tempest", "TEMPEST",
     "SPELL SCROLL. A WHIRLWIND TRAPS ONE MONSTER YOU CHOOSE. IT MISSES ITS "
     "NEXT TURN. SCROLL CRUMBLES.", 0, ALL),
    ("dragon_spear", "DRAGON SPEAR",
     "WEAPON. 3 ATTACK DICE, 4 AGAINST A DRAGON. ATTACKS DIAGONALLY.",
     0, NOT_WIZARD),
    ("ring_return", "RING OF RETURN",
     "RETURNS EVERY HERO THE WEARER CAN SEE TO THE QUEST START. ONCE ONLY.",
     0, ALL),
    ("dagger", "THROWING DAGGER",
     "ALWAYS INFLICTS 1 BODY POINT ON A MONSTER YOU CAN SEE. IT CANNOT DEFEND. "
     "THE DAGGER IS LOST.", 0, ALL),
    ("holy_water", "HOLY WATER",
     "USE INSTEAD OF ATTACKING. KILLS ANY SKELETON, ZOMBIE OR MUMMY. "
     "DISCARD AFTER USE.", 400, ALL),
    ("crossbow", "CROSSBOW",
     "WEAPON. 3 COMBAT DICE. FIRE AT ANY MONSTER YOU SEE, BUT NOT ONE NEXT TO "
     "YOU. ARROWS NEVER RUN OUT.", 350, NOT_WIZARD),
    ("battle_axe", "BATTLE AXE",
     "WEAPON. 4 COMBAT DICE. NO SHIELD WHILE YOU CARRY IT.", 450, NOT_WIZARD),
]


def lines_for(card, width):
    """Title, wrapped body, then the price. Every line fits in `width`."""
    _, title, body, price, _ = card
    out = [title] + textwrap.wrap(body, width)
    if price:
        out.append(f"{price} GOLD COINS")
    return out


def check(card, lines, width):
    ident, title = card[0], card[1]
    problems = []
    for line in lines:
        bad = sorted(set(line) - LEGAL)
        if bad:
            problems.append(f"{ident}: unprintable {bad} in {line!r}")
        if len(line) > width:
            problems.append(f"{ident}: {len(line)} > {width} cols: {line!r}")
    if len(title) > width:
        problems.append(f"{ident}: title too long")
    return problems


def emit(path, width):
    problems, blocks = [], []
    for card in CARDS:
        lines = lines_for(card, width)
        problems += check(card, lines, width)
        blocks.append((card, lines))
    if problems:
        for p in problems:
            print("!!", p)
        return 1

    with open(path, "w") as fh:
        fh.write("; card_text.asm -- GENERATED by card_text.py, do not edit.\n")
        fh.write(f"; {len(CARDS)} cards, wrapped to {width} columns.\n")
        fh.write("; Each record: class mask, line count, then NUL terminated\n")
        fh.write("; lines - title first, price last.\n\n")
        fh.write("CARD_BARBARIAN      equ %00000001\n")
        fh.write("CARD_DWARF          equ %00000010\n")
        fh.write("CARD_ELF            equ %00000100\n")
        fh.write("CARD_WIZARD         equ %00001000\n\n")
        fh.write(f"card_count          equ {len(CARDS)}\n")
        fh.write(f"card_columns        equ {width}\n\n")
        fh.write("card_table:\n")
        for card, _ in blocks:
            fh.write(f"                    dw card_{card[0]}\n")
        fh.write("\n")
        for card, lines in blocks:
            fh.write(f"card_{card[0]}:\n")
            fh.write(f"                    db %{card[4]:08b}"
                     f"           ; classes\n")
            fh.write(f"                    db {len(lines)}\n")
            for line in lines:
                fh.write(f'                    db "{line}", 0\n')
            fh.write("\n")
    longest = max(len(l) for _, ls in blocks for l in ls)
    total = sum(len(l) + 1 for _, ls in blocks for l in ls) + 2 * len(CARDS)
    print(f"{path}: {len(CARDS)} cards, longest line {longest}/{width}, "
          f"{total} bytes of text")
    return 0


def render_preview(path, width):
    """Draw the wrapped text with the real font, so glyph gaps are visible."""
    import numpy as np
    from PIL import Image

    font_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), FONT)
    glyphs = np.unpackbits(
        np.frombuffer(open(font_path, "rb").read(), dtype=np.uint8).reshape(-1, 8),
        axis=1).reshape(-1, 8, 8)

    blocks = [lines_for(c, width) for c in CARDS]
    rows = max(len(b) for b in blocks) + 1
    cols, per_row = width, 2
    sheet_w = per_row * (cols * 8 + 16)
    sheet_h = ((len(blocks) + per_row - 1) // per_row) * (rows * 8 + 16)
    sheet = np.zeros((sheet_h, sheet_w), dtype=np.uint8)
    for i, lines in enumerate(blocks):
        ox = (i % per_row) * (cols * 8 + 16) + 8
        oy = (i // per_row) * (rows * 8 + 16) + 8
        for r, line in enumerate(lines):
            for c, ch in enumerate(line):
                g = glyphs[ord(ch) - 32]
                sheet[oy + r * 8:oy + r * 8 + 8, ox + c * 8:ox + c * 8 + 8] = g
    img = Image.fromarray(np.where(sheet, 255, 0).astype(np.uint8))
    img = img.resize((img.width * 2, img.height * 2), Image.NEAREST)
    img.save(path)
    print(f"preview: {path}")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--width", type=int, default=32, help="columns (32)")
    ap.add_argument("--out", default="card_text.asm")
    ap.add_argument("--preview", action="store_true",
                    help="render the text in the HeroQuest font")
    args = ap.parse_args()

    rc = emit(args.out, args.width)
    if rc == 0 and args.preview:
        render_preview(os.path.splitext(args.out)[0] + "_preview.png", args.width)
    return rc


if __name__ == "__main__":
    sys.exit(main())
