; card_text.asm -- GENERATED by card_text.py, do not edit.
; 17 cards, wrapped to 32 columns.
; Each record: class mask, line count, then NUL terminated
; lines - title first, price last.

CARD_BARBARIAN      equ %00000001
CARD_DWARF          equ %00000010
CARD_ELF            equ %00000100
CARD_WIZARD         equ %00001000

card_count          equ 17
card_columns        equ 32

card_table:
                    dw card_restoration
                    dw card_speed
                    dw card_antidote
                    dw card_healing
                    dw card_dexterity
                    dw card_defense
                    dw card_battle
                    dw card_crown
                    dw card_acid_oil
                    dw card_lightning
                    dw card_tempest
                    dw card_dragon_spear
                    dw card_ring_return
                    dw card_dagger
                    dw card_holy_water
                    dw card_crossbow
                    dw card_battle_axe

card_restoration:
                    db %00001111           ; classes
                    db 4
                    db "POTION OF RESTORATION", 0
                    db "RESTORES 1 LOST BODY POINT AND 1", 0
                    db "LOST MIND POINT.", 0
                    db "300 GOLD COINS", 0

card_speed:
                    db %00001111           ; classes
                    db 5
                    db "POTION OF SPEED", 0
                    db "ROLL TWICE AS MANY DICE THE NEXT", 0
                    db "TIME YOU MOVE. DRINK AT ANY", 0
                    db "TIME.", 0
                    db "200 GOLD COINS", 0

card_antidote:
                    db %00001111           ; classes
                    db 5
                    db "VENOM ANTIDOTE", 0
                    db "HEALS UP TO 2 BODY POINTS OF", 0
                    db "DAMAGE FROM POISON NEEDLES OR", 0
                    db "DARTS ONLY.", 0
                    db "300 GOLD COINS", 0

card_healing:
                    db %00001111           ; classes
                    db 5
                    db "POTION OF HEALING", 0
                    db "RESTORES BODY POINTS EQUAL TO 1", 0
                    db "RED DIE, UP TO YOUR STARTING", 0
                    db "TOTAL. DRINK AT ANY TIME.", 0
                    db "500 GOLD COINS", 0

card_dexterity:
                    db %00001111           ; classes
                    db 5
                    db "POTION OF DEXTERITY", 0
                    db "ADDS 5 SQUARES TO YOUR NEXT", 0
                    db "MOVE, OR MAKES ONE PIT JUMP", 0
                    db "SUCCEED. ONE POTION PER TURN.", 0
                    db "100 GOLD COINS", 0

card_defense:
                    db %00001111           ; classes
                    db 4
                    db "POTION OF DEFENSE", 0
                    db "2 EXTRA COMBAT DICE THE NEXT", 0
                    db "TIME YOU DEFEND. DRINK AT ANY", 0
                    db "TIME.", 0

card_battle:
                    db %00001111           ; classes
                    db 3
                    db "POTION OF BATTLE", 0
                    db "REROLL YOUR ATTACK DICE ONCE.", 0
                    db "200 GOLD COINS", 0

card_crown:
                    db %00001111           ; classes
                    db 4
                    db "CROWN OF SHADOWS", 0
                    db "ARMOR. 1 EXTRA DEFEND DIE. YOU", 0
                    db "SEE NORMALLY IN DARKNESS,", 0
                    db "MAGICAL AND NOT.", 0

card_acid_oil:
                    db %00001111           ; classes
                    db 3
                    db "OIL OF ACID IMMUNITY", 0
                    db "AVOID ALL ACID DAMAGE FOR ONE", 0
                    db "QUEST. DISCARD AFTER USE.", 0

card_lightning:
                    db %00001111           ; classes
                    db 5
                    db "LIGHTNING BOLT", 0
                    db "SPELL SCROLL. THE BOLT FLIES", 0
                    db "STRAIGHT UNTIL IT HITS A WALL OR", 0
                    db "SHUT DOOR. 2 BODY POINTS TO ALL", 0
                    db "IN ITS PATH. SCROLL CRUMBLES.", 0

card_tempest:
                    db %00001111           ; classes
                    db 5
                    db "TEMPEST", 0
                    db "SPELL SCROLL. A WHIRLWIND TRAPS", 0
                    db "ONE MONSTER YOU CHOOSE. IT", 0
                    db "MISSES ITS NEXT TURN. SCROLL", 0
                    db "CRUMBLES.", 0

card_dragon_spear:
                    db %00000111           ; classes
                    db 3
                    db "DRAGON SPEAR", 0
                    db "WEAPON. 3 ATTACK DICE, 4 AGAINST", 0
                    db "A DRAGON. ATTACKS DIAGONALLY.", 0

card_ring_return:
                    db %00001111           ; classes
                    db 4
                    db "RING OF RETURN", 0
                    db "RETURNS EVERY HERO THE WEARER", 0
                    db "CAN SEE TO THE QUEST START. ONCE", 0
                    db "ONLY.", 0

card_dagger:
                    db %00001111           ; classes
                    db 4
                    db "THROWING DAGGER", 0
                    db "ALWAYS INFLICTS 1 BODY POINT ON", 0
                    db "A MONSTER YOU CAN SEE. IT CANNOT", 0
                    db "DEFEND. THE DAGGER IS LOST.", 0

card_holy_water:
                    db %00001111           ; classes
                    db 5
                    db "HOLY WATER", 0
                    db "USE INSTEAD OF ATTACKING. KILLS", 0
                    db "ANY SKELETON, ZOMBIE OR MUMMY.", 0
                    db "DISCARD AFTER USE.", 0
                    db "400 GOLD COINS", 0

card_crossbow:
                    db %00000111           ; classes
                    db 6
                    db "CROSSBOW", 0
                    db "WEAPON. 3 COMBAT DICE. FIRE AT", 0
                    db "ANY MONSTER YOU SEE, BUT NOT ONE", 0
                    db "NEXT TO YOU. ARROWS NEVER RUN", 0
                    db "OUT.", 0
                    db "350 GOLD COINS", 0

card_battle_axe:
                    db %00000111           ; classes
                    db 4
                    db "BATTLE AXE", 0
                    db "WEAPON. 4 COMBAT DICE. NO SHIELD", 0
                    db "WHILE YOU CARRY IT.", 0
                    db "450 GOLD COINS", 0

