#!/usr/bin/env python
"""Quest and board exporter.

Writes the two generated halves of the quest data:

    data/board.asm       the 22 room rectangles, once, shared by every quest
    data/quest_data.asm  a header and six lists per quest

The row shapes below are game/quest_structures.i, and nothing else in the
tree should be inventing them.

The board comes out of assets/coremap_origzx.png -- the room map painted in
assets/quests/quests.hipnc, one flat colour per region, 26x19 squares inside
an 11px/16px border. Rooms are rectangles; the corridor is the ring and the
cross and is not a region as far as the game is concerned, it is id 0.

    THE BOARD HALF IS NOT RIGHT YET AND data/board.asm IS NOT IN THE BUILD.

It comes out with 21 rooms and not 22, and the fault is one square. (17,13)
is painted room17's grey in the png, and /obj/heroquest_base in the .hip
agrees -- its room21 group holds 15 prims. But map-ai-parsing/work/rooms.json
records room21 as a 4x4 at (17,10), which would cover (17,13) as well, and
room17 as a 4x5 at (14,13), which already covers it. The two overlap on that
one square, so room21 measures 15, fails the "fills its bounding box" test,
and is dropped.

Exactly one of those rectangles is wrong and nothing here can say which:
give (17,13) to room21 and room17 becomes 19 squares, keep it in room17 and
room21 stays 15, and game/quest_structures.i needs every room to be a
rectangle either way. It wants checking against the printed board.

So board.asm is written but heroques.asm does not include it -- its ASSERT on
ROOM_COUNT would fail the build. It also has no SLOT/PAGE/org of its own and
would need one: room_of is built from these rectangles at boot, so unlike the
quests they have to be readable without paging.

The quests come out of assets/quests/quests_data.json, which is what
map-ai-parsing reads off the scans. That covers the map half of a quest and
all of it:

    title, staircase square, wandering monster
    doors        (x, y, north|west)
    monsters     (type, x, y)
    furniture    (kind, x, y, orientation)

and none of the half that is text rather than picture, because the quest
notes on the bottom of each page have not been transcribed:

    briefing, objective, traps, finds, triggers, and which figure is the
    NPC or the objective's target

Those get their labels and an empty list each, so the counts come out zero
and the rows can be dropped in later without moving anything. A quest with
every count at zero is legal - the party is put down on the stairs and
walking back up wins it - so the campaign is playable from this file as it
stands, it is just not yet the campaign the book describes.

Doors are canonical: every one is written as the NORTH or the WEST wall of
its square. quests_data.json already records them that way, so there is
nothing to flip here - the flip happened in map-ai-parsing/work/04_doors.py.
"""

import argparse
import json
import os
from collections import deque

import numpy as np
from PIL import Image

QUEST_HEADER = '''\
;=============================================================================
; quest_data - the quests themselves, in a bank of their own
;=============================================================================
; GENERATED by assets/quests_to_asm.py from assets/quests/quests_data.json.
; Do not edit: the map half is read off the scans by map-ai-parsing and a fix
; belongs there. The text half - briefings, traps, finds, triggers - is not
; transcribed yet and comes out as empty lists; when it is written it will
; want a source file of its own beside quests_data.json, not hand edits here.
;
; Placement:  SLOT 3, PAGE 1, org $C000 - bank 1, borrowed. Nothing here is
;             ever executed and nothing here may be read unless the bank is
;             paged in. Banks 1 and 3 are the only free ones left (0 scenes,
;             2 core, 4 card text, 5 the game, 6 music) and both are
;             contended - which costs nothing here, because a quest is read
;             once, by quest.load, and never again during play.
; Depends on: MENU_STRING from game/menus/menu_structures.i, the records in
;             game/quest_structures.i, and the MT_ ids in game/globals.asm.
; Namespace:  MODULE quest_data. The campaign is the pointer table at the
;             bottom; quest.load is the only thing that should reach in.
;
; A word of warning about who may read this bank: a scene cannot. Every scene
; is PAGE 0 at this same slot, so a quest-select menu that paged this in
; would page itself out - the trap game/items.asm describes. Whatever draws a
; title from here has to live in page 5, the way game/card_text.asm does for
; the card descriptions.
;
; Every count in a header is label arithmetic and not a literal, so a row
; added by hand cannot be added and forgotten.
;
; There is no WRAP here, though the briefings will be wrapped to 28 columns
; like card_data's descriptions are. data/card_data.asm defines that constant
; and is included first, so a second one is a duplicate-label error - and
; nothing in this file needs it at assembly time anyway, because the wrapping
; happens in the exporter, before a line is ever written.
;=============================================================================

                    SLOT 3
                    PAGE 1
                    org $C000
                    MODULE quest_data

;-----------------------------------------------------------------------------
; The titles. Uppercase, like every other title in the game - the briefings
; below are mixed case, the font has both.
;
; Keep them short: a title is drawn as one MenuString on one row, so 28
; columns is the wall.
;-----------------------------------------------------------------------------
'''

BRIEFINGS = '''
;-----------------------------------------------------------------------------
; The briefings - the parchment read out before the party goes down - are not
; here, because the quest notes on the bottom half of the pages have not been
; transcribed. Every Quest.BRIEF_STR below is 0, which the drawer reads as
; "no parchment" and skips.
;
; When they are written, they go here in the shape card_data uses - a line
; count, then that many MenuStrings, wrapped to WRAP columns at write time so
; nothing has to word-wrap at runtime:
;
;       b_q01:      db 3
;                   MENU_STRING "..."
;
; and the 0 in the header becomes b_q01.
;-----------------------------------------------------------------------------

'''

CAMPAIGN = '''
;-----------------------------------------------------------------------------
; The campaign - the order they are played in, and the only thing outside
; this file that has to know how many there are. QUEST_COUNT counts the
; table, so adding a quest is one line here and nothing else.
;-----------------------------------------------------------------------------
quests:
%(rows)s
quests_end:

QUEST_COUNT         equ (quests_end - quests) / 2

; Ten in this release. Not a limit - the table is what says how many - but a
; quest that goes missing from it, or a title written without a body behind
; it, stops the build here rather than showing up as a short campaign menu.
    ASSERT QUEST_COUNT == %(n)d

BYTES               equ quests_end - t_q01

                    ASSERT BYTES < $4000        ; it has to fit the bank
                    DISPLAY "quests: ", /D, BYTES, " bytes in bank 1"

                    ENDMODULE
'''

BOARD_W, BOARD_H = 26, 19
BORDER_X, BORDER_Y = 11, 16         # the frame around the map in the png
ROOM_CORRIDOR = 0


def read_board(path):
    """Return (ids, rooms): a 19x26 array of region ids, and the rectangles.

    A region is a run of one flat colour, 4-connected. The rectangular ones
    are rooms; the ring and the cross come out as thin or L-shaped regions
    and all collapse to ROOM_CORRIDOR.
    """
    im = np.array(Image.open(path).convert("RGB")).astype(int)
    inner = im[BORDER_Y:im.shape[0] - 25, BORDER_X:im.shape[1] - 8]
    ch, cw = inner.shape[0] / BOARD_H, inner.shape[1] / BOARD_W

    cell = np.zeros((BOARD_H, BOARD_W, 3))
    for y in range(BOARD_H):
        for x in range(BOARD_W):
            py, px = int((y + 0.5) * ch), int((x + 0.5) * cw)
            patch = inner[py - 10:py + 10, px - 10:px + 10].reshape(-1, 3)
            cell[y, x] = np.median(patch, axis=0)

    lab = -np.ones((BOARD_H, BOARD_W), int)
    n = 0
    for y in range(BOARD_H):
        for x in range(BOARD_W):
            if lab[y, x] >= 0:
                continue
            q = deque([(y, x)])
            lab[y, x] = n
            while q:
                cy, cx = q.popleft()
                for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    ny, nx = cy + dy, cx + dx
                    if (0 <= ny < BOARD_H and 0 <= nx < BOARD_W
                            and lab[ny, nx] < 0
                            and np.abs(cell[ny, nx] - cell[cy, cx]).max() <= 25):
                        lab[ny, nx] = n
                        q.append((ny, nx))
            n += 1

    # A room is a region that FILLS its bounding box. The corridor comes out
    # as the thin strips and the L-shaped corners of the ring and the cross,
    # and every one of those fails the test - which is the whole rule.
    #
    # Anything left over that is neither is a fault in the map, not a shape
    # the game supports, so it is handed back to be complained about rather
    # than quietly rounded into a corridor.
    boxes, odd = [], []
    for i in range(n):
        ys, xs = np.where(lab == i)
        x0, y0 = xs.min(), ys.min()
        w, h = xs.max() - x0 + 1, ys.max() - y0 + 1
        if w * h == len(xs) and w > 1 and h > 1:
            boxes.append((x0, y0, w, h, len(xs), i))
        elif w > 1 and h > 1 and len(xs) >= 0.75 * w * h:
            # A bend in the corridor fills about half of its box; a room with
            # a square painted the wrong colour fills nearly all of it.
            odd.append((x0, y0, w, h, len(xs), i))

    boxes.sort(key=lambda r: (r[1], r[0]))      # reading order, top-left first
    rooms, ids = [], np.zeros((BOARD_H, BOARD_W), int)
    for n_room, (x0, y0, w, h, _, i) in enumerate(boxes, start=1):
        rooms.append((x0, y0, w, h))
        ids[lab == i] = n_room                  # 1..ROOM_COUNT, 0 = corridor
    return ids, rooms, odd


def write_board(rooms, out):
    with open(out, "w") as f:
        f.write("; board - GENERATED by assets/quests_to_asm.py, do not edit\n")
        if len(rooms) != 22:
            f.write("; \n; NOT IN THE BUILD: this is %d rooms and the game wants"
                    " 22, so the\n; ASSERT below fails. See the module docstring"
                    " in quests_to_asm.py -\n; one square, (17,13), is claimed by"
                    " two room rectangles at once.\n; \n" % len(rooms))
        f.write("rooms:\n")
        for x, y, w, h in rooms:
            f.write("                    Room {%2d, %2d, %d, %d}\n" % (x, y, w, h))
        f.write("rooms_end:\n\n")
        f.write("    ASSERT (rooms_end - rooms) / Room == ROOM_COUNT\n")


# The pack renames the base roster and adds nothing to it. Eight of the nine
# names are plain; two are the classic reskin, and one is an elimination:
# every base monster turns up in the ten maps except the Fimir, and every
# parsed type is accounted for except "abomination", so that is the Fimir.
MONSTER = {
    "goblin": "MT_GOBLIN",
    "orc": "MT_ORC",
    "abomination": "MT_FIMIR",
    "skeleton": "MT_SKELETON",
    "zombie": "MT_ZOMBIE",
    "mummy": "MT_MUMMY",
    "dread_warrior": "MT_CHAOS_WARRIOR",
    "gargoyle": "MT_GARGOYLE",
    "dread_sorcerer": "MT_CHAOS_SORCERER",
}

# "unknown" is not a monster. It is one square of quest 10's dragon lair
# artwork that came out green enough to pass step 5's test - there is no icon
# on it, and the two mummies either side of it are the real ones. Dropped
# here rather than emitted as a figure standing in the middle of a drawing.
NOT_A_MONSTER = ("unknown",)

FURNITURE = {
    "stairway": "FURN_STAIRWAY", "table": "FURN_TABLE", "throne": "FURN_THRONE",
    "bookcase": "FURN_BOOKCASE", "chest": "FURN_CHEST", "rack": "FURN_RACK",
    "weapon_rack": "FURN_WEAPON_RACK", "tomb": "FURN_TOMB",
    "alchemist_bench": "FURN_ALCHEMIST", "altar": "FURN_ALTAR",
    "bed": "FURN_BED", "cage": "FURN_CAGE", "column": "FURN_COLUMN",
    "dread_skull": "FURN_DREAD_SKULL", "forge": "FURN_FORGE",
    "loom": "FURN_LOOM", "machine": "FURN_MACHINE",
    "stone_bench": "FURN_STONE_BENCH", "tomb_sword": "FURN_TOMB_SWORD",
    "rubble": "FURN_RUBBLE", "trapdoor": "FURN_TRAPDOOR",
    "lair_art": "FURN_LAIR_ART", "barrel": "FURN_BARREL",
}

# The pool quest.load copies into. Going over is not a build error - the rows
# are legal in the bank either way - but the loader refuses the rows it has no
# room for, so it is worth saying out loud.
LIMITS = dict(doors=32, monsters=24, furniture=24, traps=12, finds=16,
              triggers=16)
MAX_MONSTERS = 32
WRAP = 28           # columns a title or a briefing line is drawn in

PAD = " " * 20


def canonical_shapes(sprite_index):
    """{kind: (w, h)} - the footprint a piece has when it is not turned.

    Taken from the sprite index, because step 11 already had to answer this
    to cut one image per kind, and two answers would eventually differ.
    """
    if not os.path.exists(sprite_index):
        return {}
    idx = json.load(open(sprite_index))["sprites"].get("furniture", {})
    return {k: (v["w"], v["h"]) for k, v in idx.items()}


def orient_of(kind, w, h, shapes, odd):
    """DIR_ for a piece whose footprint on this map is w x h.

    Only bit 0 of the orientation changes the footprint, so there are two
    answers to choose between: the piece as its type describes it, or that
    turned a quarter. An exact transpose is the one confident signal there
    is, and anything else is left unturned and counted.

    It is left unturned rather than guessed because a footprint in
    quests_data.json is the INK BOUNDING BOX of the drawing, not the tile's
    true square count - so a piece half hidden behind a monster measures
    small, and one drawn with a flourish measures large. Getting this right
    needs the FurnitureType table, which needs the sprites, which do not
    exist yet.
    """
    base = shapes.get(kind)
    if base is None or (w, h) == base:
        return "DIR_NORTH"
    if (w, h) == (base[1], base[0]):
        return "DIR_EAST"
    odd.append("%s %dx%d/%dx%d" % (kind, w, h, base[0], base[1]))
    return "DIR_NORTH"


def start_square(q, quest, warn):
    """Where the party is put down: the stairway, if the map draws one.

    Eight of the ten do. Quests 5 and 10 draw none, and both draw escape
    arrows instead - the way out, which is the same square as the way in
    everywhere else - so that is the fallback, and it is a guess.
    """
    for x0, y0, x1, y1, kind in quest["furniture"]:
        if kind == "stairway":
            return x0, y0
    if quest["arrows"]:
        x, y, _ = quest["arrows"][0]
        warn.append("no stairway on the map; start square taken from the "
                    "escape arrow at (%d,%d) - CHECK IT" % (x, y))
        return x, y
    warn.append("no stairway and no escape arrow - start square left at (0,0)")
    return 0, 0


def quest_rows(q, quest, shapes, warn, odd):
    """The six lists of one quest, as lines of asm."""
    out = []

    out.append("; Doors. Always the north or the west wall of the square named.")
    out.append("q%s_doors:" % q)
    for x, y, o in quest["doors"]:
        flag = " | D_WEST" if o == "W" else ""
        out.append("%sDoor {%d%s, %d}%s; %s wall of (%d,%d)"
                   % (PAD, x, flag, y, " " * max(1, 26 - len("%d%s, %d" % (x, flag, y))),
                      "west" if o == "W" else "north", x, y))
    out.append("q%s_doors_end:" % q)
    out.append("")

    out.append("; The roster. The square says which room the figure is in.")
    out.append("q%s_monsters:" % q)
    for x, y, t in quest["monsters"]:
        if t in NOT_A_MONSTER:
            warn.append("dropped a %r at (%d,%d) - see NOT_A_MONSTER" % (t, x, y))
            continue
        if t not in MONSTER:
            raise SystemExit("quest %s: no MT_ for monster %r" % (q, t))
        out.append("%sQuestMonster {globals.%s, %d, %d}" % (PAD, MONSTER[t], x, y))
    out.append("q%s_monsters_end:" % q)
    out.append("")

    out.append("; Furniture. X,Y is the top-left square it covers once turned.")
    out.append("q%s_furniture:" % q)
    for x0, y0, x1, y1, kind in quest["furniture"]:
        if kind not in FURNITURE:
            raise SystemExit("quest %s: no FURN_ for furniture %r" % (q, kind))
        d = orient_of(kind, x1 - x0 + 1, y1 - y0 + 1, shapes, odd)
        turn = "" if d == "DIR_NORTH" else " | (%s << F_ORIENT_SHIFT)" % d
        out.append("%sFurniture {%s%s, %d, %d}" % (PAD, FURNITURE[kind], turn, x0, y0))
    out.append("q%s_furniture_end:" % q)
    out.append("")

    # The text half. Labels only, so the counts come out zero and a row can be
    # added without anything else moving.
    for name, what in (("traps", "the orange and deep-red squares, once the "
                                 "notes say what they are"),
                       ("finds", "what a search of each room turns up"),
                       ("triggers", "the story")):
        out.append("q%s_%s:%s; %s" % (q, name, " " * max(1, 18 - len(q) - len(name)), what))
        out.append("q%s_%s_end:" % (q, name))
        out.append("")
    return out


def write_quests(quests, sprite_index, out):
    shapes = canonical_shapes(sprite_index)
    warnings = {}
    body = []

    for q in sorted(quests):
        d = quests[q]
        warn, odd = [], []
        rows = quest_rows(q, d, shapes, warn, odd)
        sx, sy = start_square(q, d, warn)
        if len(d["title"]) > WRAP:
            warn.append("the title is %d columns and the row is %d - it will "
                        "be drawn cut off" % (len(d["title"]), WRAP))
        if odd:
            warn.append("%d of %d furniture footprints are neither the type's "
                        "shape nor its transpose, so they are emitted unturned "
                        "(they are ink bounding boxes, not tile sizes): %s"
                        % (len(odd), len(d["furniture"]), ", ".join(odd)))
        live = sum(1 for m in d["monsters"] if m[2] not in NOT_A_MONSTER)
        if live > MAX_MONSTERS:
            warn.append("%d figures against MAX_MONSTERS %d - the loader will "
                        "refuse the last %d if they are ever all live at once"
                        % (live, MAX_MONSTERS, live - MAX_MONSTERS))
        if d["wandering"] not in MONSTER:
            raise SystemExit("quest %s: no MT_ for wandering %r" % (q, d["wandering"]))
        if warn:
            warnings[q] = warn

        counts = ", ".join("(q%s_%s_end-q%s_%s)/%s" % (q, n, q, n, s) for n, s in (
            ("doors", "Door"), ("monsters", "QuestMonster"),
            ("furniture", "Furniture"), ("traps", "Trap"),
            ("finds", "Find"), ("triggers", "Trigger")))

        body.append(";" + "-" * 76)
        body.append("; Quest %d - %s" % (d["n"], d["title"]))
        body.append("; %d squares in play, %d doors, %d figures, %d pieces of furniture."
                    % (sum(r.count("o") for r in d["grid"]), len(d["doors"]),
                       live, len(d["furniture"])))
        body.append("; Marked on the map, and waiting on the notes: %s"
                    % (", ".join(sorted({m[2] for m in d["marks"]})) or "nothing"))
        for w in warn:
            body.append("; NOTE: %s" % w)
        body.append(";" + "-" * 76)
        body.append("q%s:%sQuest {t_q%s, 0, 0, %d, %d, globals.%s, OBJ_EXIT, 0, 0, %s}"
                    % (q, " " * max(1, 20 - len(q) - 2), q, sx, sy,
                       MONSTER[d["wandering"]], counts))
        body.append("")
        body.extend(rows)

    with open(out, "w") as f:
        f.write(QUEST_HEADER)
        for q in sorted(quests):
            f.write('t_q%s:%sMENU_STRING "%s"\n'
                    % (q, " " * max(1, 20 - len(q) - 4), quests[q]["title"].upper()))
        f.write(BRIEFINGS)
        f.write("\n".join(body))
        f.write(CAMPAIGN % dict(n=len(quests),
                                rows="\n".join(
                                    PAD + "dw " + ", ".join("q%02d" % i for i in r)
                                    for r in (range(1, 6), range(6, 11)))))
    return warnings


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--map", default="coremap_origzx.png",
                    help="the room map painted in quests/quests.hipnc")
    ap.add_argument("--board-out", default="../data/board.asm")
    ap.add_argument("--quests", default="quests/quests_data.json",
                    help="what map-ai-parsing read off the scans")
    ap.add_argument("--quest-out", default="../data/quest_data.asm")
    ap.add_argument("--sprites", default="quests/sprites/index.json",
                    help="only for the unturned footprint of each furniture kind")
    ap.add_argument("--print", action="store_true",
                    help="draw the map as # and . and stop")
    a = ap.parse_args()

    ids, rooms, odd = read_board(a.map)
    for x, y, w, h, cells, _ in odd:
        print("map fault: region at (%d,%d) is %dx%d but has %d squares - "
              "not a rectangle, so it is not a room" % (x, y, w, h, cells))
    if a.print:
        for row in ids:
            print("".join("#" if v else "." for v in row))
        print("%d rooms" % len(rooms))
        return
    write_board(rooms, a.board_out)
    print("%d rooms -> %s" % (len(rooms), a.board_out))

    quests = json.load(open(a.quests))["quests"]
    warnings = write_quests(quests, a.sprites, a.quest_out)
    print("%d quests -> %s" % (len(quests), a.quest_out))
    for q in sorted(warnings):
        for w in warnings[q]:
            print("  quest %s: %s" % (q, w))


if __name__ == "__main__":
    main()
