; card1_08: 2640 bytes, 15 bytes per row
card1_08:
        defb $3F, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $F8
        defb $7D, $FD, $DB, $BF, $FF, $F6, $EF, $FF, $FF, $FF, $EF, $FF, $FF, $FF, $FE
        defb $F7, $F7, $7E, $FF, $FB, $77, $BD, $F7, $7D, $FF, $EF, $FE, $FB, $6D, $BE
        defb $DF, $FF, $F7, $FF, $FF, $FD, $FF, $FF, $7D, $FB, $FD, $BB, $DF, $F7, $EF
        defb $FF, $9D, $BF, $FF, $E6, $ED, $DA, $FB, $FF, $BF, $DF, $FF, $F7, $BD, $FB
        defb $7F, $F7, $FF, $FF, $FF, $EF, $FF, $FF, $FF, $FF, $DF, $FD, $BF, $FF, $BF
        defb $FE, $FE, $FF, $7B, $3D, $FB, $FF, $FF, $7F, $FF, $FE, $DF, $FB, $77, $EF
        defb $FF, $FB, $FD, $EF, $FF, $B7, $E6, $F7, $FF, $F7, $BB, $FF, $7F, $FF, $7B
        defb $F7, $9F, $EF, $BD, $EF, $FF, $CC, $23, $61, $FF, $FF, $FF, $FD, $DB, $FD
        defb $FE, $FF, $BE, $FF, $FF, $6D, $CC, $63, $21, $DF, $F7, $F2, $FF, $7F, $EF
        defb $FB, $EF, $F7, $F9, $DB, $FF, $C8, $C2, $23, $FF, $BE, $F2, $3F, $FE, $FB
        defb $FF, $BE, $FF, $F1, $FF, $DF, $01, $C2, $CF, $EF, $FF, $FB, $87, $DB, $BF
        defb $DE, $FF, $F3, $33, $3D, $FF, $0C, $52, $03, $FF, $DF, $B9, $E9, $FF, $EF
        defb $F7, $FF, $C3, $36, $37, $F7, $AB, $DB, $6F, $FD, $FB, $FD, $F2, $3D, $FB
        defb $FD, $FB, $9E, $0C, $BF, $BF, $F3, $FF, $FF, $FF, $FE, $FD, $FF, $8F, $BF
        defb $EF, $FF, $7E, $49, $AF, $9B, $F7, $FC, $7F, $1F, $DF, $FF, $FF, $F3, $F7
        defb $FB, $FE, $FE, $7F, $6F, $9F, $F7, $F8, $73, $1F, $FF, $DF, $FE, $79, $FD
        defb $FF, $98, $0E, $7F, $49, $9F, $FF, $F0, $73, $3E, $EF, $FF, $FE, $78, $EF
        defb $EF, $98, $06, $00, $59, $BF, $DF, $E0, $63, $3E, $67, $F7, $FE, $60, $7B
        defb $BF, $08, $06, $26, $D9, $9E, $C7, $E3, $66, $04, $63, $F3, $3E, $60, $7F
        defb $FF, $19, $0C, $F4, $D9, $9C, $C1, $C7, $60, $04, $63, $E3, $36, $C4, $7F
        defb $FF, $19, $38, $64, $D8, $98, $CF, $CE, $00, $3C, $E1, $C3, $A6, $CE, $7F
        defb $EE, $18, $79, $24, $90, $98, $53, $8E, $02, $78, $C0, $C1, $26, $8F, $3B
        defb $FE, $58, $F1, $A0, $90, $99, $47, $8E, $06, $78, $48, $4D, $84, $9C, $BF
        defb $FE, $79, $F3, $A2, $12, $33, $0F, $83, $6E, $78, $4C, $0D, $00, $80, $77
        defb $FE, $70, $F3, $B2, $32, $30, $1C, $80, $EE, $70, $0C, $8D, $90, $84, $3F
        defb $DC, $E0, $00, $22, $36, $18, $D3, $60, $4C, $C0, $E8, $89, $11, $FC, $BF
        defb $FC, $8B, $90, $26, $36, $3F, $9B, $78, $4C, $C2, $49, $81, $11, $F8, $7F
        defb $F8, $3B, $F8, $66, $33, $3F, $EC, $FC, $4C, $E2, $43, $83, $31, $F1, $7B
        defb $FC, $73, $FF, $E7, $27, $1F, $B5, $90, $DC, $63, $46, $7F, $39, $E3, $FF
        defb $F4, $F3, $FF, $F3, $25, $3F, $9B, $61, $DC, $C6, $49, $BF, $99, $E6, $FF
        defb $F4, $FB, $FF, $F6, $25, $BF, $EE, $63, $FC, $A3, $7F, $BF, $B9, $CC, $EF
        defb $FB, $FF, $DF, $EF, $BC, $FF, $CD, $87, $FD, $BD, $FD, $FF, $FF, $8B, $FD
        defb $FB, $FE, $FD, $F3, $BF, $DF, $E7, $8F, $F8, $9D, $FD, $FB, $FF, $2B, $FF
        defb $FB, $FF, $BF, $7F, $B7, $9F, $E7, $1F, $F9, $DE, $ED, $FE, $FC, $FF, $F3
        defb $FA, $7F, $FB, $EF, $7F, $6F, $F6, $7F, $F9, $DE, $FF, $77, $FC, $FF, $FF
        defb $FE, $F6, $FE, $EE, $6F, $7F, $F2, $FF, $E1, $DF, $BF, $7D, $F3, $FF, $CF
        defb $FE, $9F, $F7, $F7, $FE, $FF, $F3, $FF, $FB, $DB, $FE, $FF, $BB, $FF, $7F
        defb $FF, $27, $DF, $77, $FB, $DF, $F3, $FF, $FB, $DF, $FE, $F7, $E7, $FF, $7F
        defb $FD, $FB, $FD, $F3, $FF, $F7, $F3, $BF, $EF, $DF, $FE, $FD, $F7, $FE, $FF
        defb $FB, $F9, $BF, $FF, $FF, $FF, $F7, $FD, $FF, $DF, $FC, $FF, $E7, $E6, $FD
        defb $FB, $FE, $FB, $7B, $FF, $FF, $F7, $FF, $DF, $DF, $FC, $F7, $6F, $BF, $FF
        defb $F7, $BE, $FF, $FB, $FF, $FD, $E7, $FF, $FF, $DF, $BD, $FD, $CF, $FF, $DF
        defb $F7, $FF, $76, $FB, $F7, $FF, $E7, $DF, $FF, $9F, $FC, $EF, $EE, $DF, $FF
        defb $FE, $EF, $7F, $F3, $FF, $7F, $CF, $FF, $FF, $BF, $CE, $FF, $EF, $FB, $FB
        defb $EF, $BF, $3F, $73, $FF, $FF, $DF, $FF, $7F, $BF, $3E, $F6, $EF, $FF, $DF
        defb $ED, $F7, $77, $FF, $FF, $EF, $BF, $F7, $F7, $BC, $FE, $FF, $CF, $FF, $FF
        defb $FF, $FF, $FE, $F3, $FB, $FF, $3F, $FF, $FF, $7B, $FE, $FD, $FF, $EF, $7F
        defb $F7, $BE, $7F, $C7, $FF, $FF, $7F, $FF, $FE, $73, $FE, $F7, $CF, $7F, $F7
        defb $FE, $FB, $ED, $EF, $FF, $FE, $FF, $DF, $FE, $F7, $FF, $7F, $6F, $FF, $BF
        defb $EF, $FE, $FF, $EF, $FF, $FC, $FE, $FE, $FC, $EF, $FF, $6F, $E7, $FB, $FF
        defb $FF, $6E, $FB, $CF, $E8, $7D, $FF, $FF, $F9, $DF, $DF, $BE, $F7, $DF, $DF
        defb $F7, $FD, $BF, $D8, $0E, $7D, $FF, $FF, $F7, $DF, $FF, $BB, $E7, $FF, $FB
        defb $FF, $DD, $F7, $9F, $FF, $FD, $FB, $FB, $FB, $FE, $FF, $DF, $F9, $FE, $FF
        defb $FB, $F3, $FF, $BF, $FE, $FD, $FF, $FF, $DF, $BF, $F7, $DF, $79, $FF, $FF
        defb $BF, $E7, $EE, $3F, $FE, $BF, $FF, $BF, $F7, $BF, $7F, $CF, $FE, $1F, $FD
        defb $EE, $3F, $78, $FF, $FE, $FD, $FF, $FF, $BF, $BF, $FF, $C7, $FF, $CF, $CB
        defb $7B, $FF, $FA, $FF, $FE, $F8, $7F, $FF, $3F, $DF, $FF, $99, $DF, $E2, $3B
        defb $9F, $FF, $F8, $FE, $FD, $FA, $7E, $FC, $1E, $DF, $DF, $BC, $FF, $FF, $EF
        defb $97, $FB, $E3, $7F, $FD, $B9, $7F, $FC, $DF, $DE, $FF, $7E, $1F, $FF, $BF
        defb $F4, $FF, $0F, $7B, $F9, $F9, $3F, $F9, $3D, $DF, $FB, $7F, $C3, $78, $7F
        defb $F9, $3C, $7F, $BF, $FB, $DE, $3F, $FA, $7F, $6F, $FF, $7F, $F8, $05, $FF
        defb $FB, $21, $7F, $BF, $E7, $FF, $FF, $F9, $FF, $E7, $BF, $FF, $FF, $FF, $FD
        defb $FE, $CF, $FF, $BF, $CF, $BF, $FF, $7F, $FF, $B7, $FF, $BF, $FF, $FF, $FF
        defb $FF, $FF, $FF, $FF, $9F, $CF, $FF, $FF, $FF, $F3, $FF, $BF, $FF, $FF, $EF
        defb $FF, $FF, $FF, $BF, $3F, $7F, $FF, $FF, $FF, $DC, $EF, $9F, $BF, $FF, $FB
        defb $FF, $FF, $FF, $B0, $FF, $FF, $F7, $FF, $FF, $FC, $FF, $DE, $FF, $EF, $7F
        defb $DF, $FF, $7F, $B3, $FE, $BF, $FF, $DF, $FD, $EF, $1D, $EF, $FF, $FF, $FD
        defb $FF, $FF, $F4, $8F, $FB, $FE, $FF, $FF, $BF, $FB, $F2, $3F, $FC, $DF, $DF
        defb $FC, $07, $81, $3D, $FF, $FF, $FF, $FB, $FF, $FF, $FF, $DB, $F8, $0F, $FF
        defb $F3, $60, $FF, $FF, $E7, $FF, $EF, $FF, $FF, $FF, $EF, $ED, $83, $E1, $EF
        defb $E4, $FF, $FF, $FF, $DF, $FB, $FF, $7F, $FF, $F8, $3F, $F7, $FF, $FC, $FF
        defb $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $F7, $E7, $BF, $FF, $FF, $FF, $FF
        defb $3F, $FF, $FF, $FF, $FF, $BF, $BF, $FF, $FF, $CF, $CE, $FF, $7F, $FF, $B3
        defb $FF, $FF, $FF, $FF, $FF, $FF, $FD, $EF, $FE, $3E, $E7, $B7, $EF, $FF, $F9
        defb $FF, $FB, $BD, $FD, $FF, $FF, $FF, $FF, $FC, $F8, $7B, $FF, $C3, $7F, $FD
        defb $FB, $EF, $FF, $DF, $EF, $F7, $FF, $FF, $FB, $EF, $FD, $FD, $9B, $FE, $FC
        defb $FF, $FF, $FB, $FF, $C8, $01, $F7, $FF, $7B, $3F, $E7, $67, $DB, $FF, $FF
        defb $FD, $FF, $FF, $FF, $DF, $FC, $FF, $7F, $EC, $FF, $F3, $FF, $27, $BF, $FF
        defb $FF, $7F, $FF, $FF, $BF, $FD, $FF, $F7, $EF, $FF, $FE, $7F, $BF, $FF, $FF
        defb $FF, $FE, $FF, $BE, $79, $FB, $FF, $FF, $FF, $FF, $FF, $9C, $9C, $C1, $FF
        defb $EF, $FF, $F7, $FD, $E7, $83, $FB, $FF, $FF, $FF, $FF, $E9, $DF, $B2, $7F
        defb $FE, $FF, $FF, $F9, $9F, $FF, $FF, $FF, $7F, $FD, $FF, $FB, $FF, $FC, $F7
        defb $FF, $F9, $FF, $E3, $7F, $FF, $FF, $EF, $FB, $DF, $FF, $F7, $BF, $FF, $7F
        defb $FF, $76, $FE, $3E, $FF, $FF, $DF, $FF, $FF, $FF, $DF, $F5, $3F, $7F, $7E
        defb $FF, $F6, $3C, $FD, $FF, $FF, $FE, $FD, $FF, $FF, $FF, $F3, $7B, $DF, $7F
        defb $EF, $F9, $9E, $FB, $FF, $FF, $FF, $FF, $FF, $F7, $FB, $F6, $FF, $FF, $7F
        defb $FF, $FF, $73, $F3, $FF, $7F, $7F, $FF, $DF, $7F, $7F, $EF, $3F, $F7, $BF
        defb $FF, $FA, $7D, $E7, $FF, $F7, $FE, $FF, $FF, $FF, $FF, $FF, $9D, $FF, $BF
        defb $F0, $DF, $E6, $CF, $FB, $FF, $FE, $FB, $FB, $FF, $EF, $FF, $F7, $FF, $DF
        defb $CC, $8E, $79, $9F, $FF, $FF, $DE, $FF, $FF, $EF, $FE, $FF, $FF, $87, $DF
        defb $6F, $BF, $9E, $FF, $FF, $BD, $FF, $7F, $EF, $7F, $FF, $FF, $BF, $BF, $E7
        defb $D9, $5F, $B7, $3F, $BF, $FF, $FD, $FE, $FF, $FD, $FF, $FF, $BF, $9F, $E7
        defb $DB, $5F, $ED, $FF, $FF, $7B, $FE, $7F, $FF, $F7, $FB, $F7, $FB, $E7, $F8
        defb $CC, $DF, $E7, $FF, $F7, $7F, $BE, $7B, $EF, $77, $FF, $FF, $BF, $F3, $FB
        defb $B3, $3F, $EF, $FF, $FF, $FB, $FD, $FF, $EF, $7F, $DF, $BF, $BF, $FC, $FF
        defb $B3, $FF, $FF, $FD, $EE, $FB, $FD, $7F, $EF, $F7, $FF, $FF, $F7, $FE, $7F
        defb $FF, $FD, $DF, $FF, $FF, $7F, $FD, $3D, $EF, $77, $FF, $FF, $BF, $FF, $3F
        defb $FF, $FE, $9F, $DF, $F7, $77, $DB, $3F, $EF, $7F, $FB, $EF, $BF, $FF, $9F
        defb $FF, $DF, $BF, $FF, $FE, $FB, $FC, $FF, $EE, $F7, $BF, $FF, $BF, $7F, $CF
        defb $2F, $F7, $7F, $FE, $EE, $FB, $BF, $BF, $CE, $F7, $FF, $FF, $BF, $FF, $F3
        defb $E7, $FF, $7F, $7F, $EF, $77, $FB, $DE, $FF, $EF, $FF, $BF, $BB, $EF, $FB
        defb $F9, $BF, $7F, $F7, $FF, $77, $F2, $4F, $CE, $EF, $EF, $FF, $3F, $FF, $FC
        defb $FF, $8F, $7F, $FF, $E7, $F3, $EC, $2F, $CE, $FF, $FF, $FF, $BF, $FF, $3F
        defb $FF, $FF, $7F, $FF, $EE, $FF, $EB, $E7, $FD, $B7, $FE, $FF, $3E, $FF, $7F
        defb $BF, $FF, $7B, $DF, $F7, $72, $CF, $F2, $47, $EF, $BF, $EF, $7F, $FF, $7F
        defb $FF, $FF, $7F, $FD, $F7, $5A, $DF, $F3, $BD, $EF, $FF, $FE, $F7, $DF, $3F
        defb $DF, $FF, $BF, $FF, $F7, $7B, $6D, $B7, $AD, $BF, $FB, $FD, $FF, $FE, $BF
        defb $7F, $FF, $BF, $7F, $FF, $B7, $ED, $2E, $DB, $F7, $FF, $FB, $FF, $FF, $BF
        defb $ED, $EF, $FF, $FF, $FB, $F4, $F6, $6F, $9F, $DF, $FF, $F3, $FF, $7F, $7F
        defb $BF, $FF, $9F, $F7, $FF, $7C, $F7, $DD, $7D, $FF, $7E, $F7, $DF, $FF, $79
        defb $FF, $FD, $CF, $FF, $7D, $DE, $FD, $BE, $77, $BF, $FF, $EF, $7F, $FF, $8F
        defb $CF, $FF, $F7, $FF, $FF, $FA, $DB, $B6, $FF, $FF, $EF, $EF, $FB, $DC, $7B
        defb $FF, $BF, $FB, $FF, $FF, $6E, $7F, $DD, $BB, $7D, $FF, $BF, $FF, $FB, $3B
        defb $EF, $FF, $F9, $EF, $DD, $DF, $E6, $FD, $AE, $FF, $FF, $BF, $FF, $FF, $CD
        defb $BD, $FE, $FE, $FF, $FE, $F6, $3F, $B6, $F7, $FF, $BE, $7F, $EF, $FC, $37
        defb $F6, $FF, $FD, $FE, $FF, $BE, $F7, $7E, $FF, $FF, $FC, $FD, $FD, $E6, $FF
        defb $7E, $F7, $FC, $FF, $FF, $FF, $FF, $DF, $FF, $F7, $FD, $FF, $FF, $FE, $BF
        defb $9F, $7F, $BF, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $F3, $FF, $BF, $CF, $B7
        defb $EB, $DF, $FF, $3F, $F7, $FF, $FF, $FF, $FF, $BF, $F7, $F7, $FF, $FE, $9D
        defb $F2, $EF, $FF, $9F, $FF, $FF, $FF, $FF, $F7, $FD, $EF, $BF, $FB, $BA, $7B
        defb $9E, $3B, $FF, $9F, $BE, $F7, $BD, $F7, $BF, $FF, $EF, $FE, $FF, $EE, $5B
        defb $EF, $94, $FF, $C7, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $6D, $BF
        defb $79, $F5, $BF, $F9, $FF, $FF, $FF, $FF, $FE, $F7, $E6, $FF, $FF, $DB, $F7
        defb $DE, $7D, $6F, $FC, $7F, $BD, $EF, $7D, $EF, $FF, $E7, $F7, $A7, $76, $7D
        defb $F7, $CF, $4F, $FF, $7B, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $BB, $6F, $AF
        defb $BD, $EF, $DF, $FF, $FF, $FF, $FF, $EF, $FF, $BD, $DF, $F9, $FE, $DA, $7B
        defb $E7, $B9, $F1, $FF, $DF, $FF, $FD, $FF, $BF, $FF, $DF, $E7, $6D, $BF, $FF
        defb $FE, $FE, $7D, $FF, $FE, $F7, $BF, $FF, $FD, $FF, $FF, $9F, $BD, $EF, $ED
        defb $FF, $77, $DE, $DF, $FF, $FF, $FF, $BF, $FF, $F7, $FF, $3E, $FB, $7F, $BF
        defb $CF, $DD, $DF, $FF, $FF, $FF, $FF, $FF, $FF, $E1, $FC, $EB, $6F, $D9, $F7
        defb $F6, $FB, $73, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FD, $BE, $FF, $DF
        defb $FF, $BF, $EF, $FE, $6B, $7F, $FF, $FF, $CF, $FF, $FF, $FF, $B7, $B6, $FB
        defb $3B, $77, $BF, $BC, $02, $70, $59, $06, $4D, $8F, $37, $FF, $7F, $EF, $EF
        defb $DF, $D9, $DF, $FE, $88, $62, $11, $0E, $44, $1C, $2F, $FF, $DB, $7B, $7F
        defb $DD, $FF, $FF, $FE, $DE, $72, $90, $6E, $51, $DC, $0B, $EF, $FF, $DF, $DD
        defb $FF, $BF, $FF, $FF, $DF, $F6, $FF, $FE, $F9, $BF, $E7, $FF, $F0, $FF, $F7
        defb $FF, $97, $FF, $EF, $FF, $FF, $F9, $FF, $FF, $FF, $DD, $FF, $F8, $FE, $DF
        defb $B7, $1F, $2D, $CE, $10, $3B, $F8, $7F, $DF, $FD, $9F, $EE, $F9, $FF, $FB
        defb $FE, $1F, $08, $80, $00, $33, $F8, $10, $C1, $0C, $93, $FE, $77, $87, $FF
        defb $CC, $3F, $20, $10, $E4, $F3, $F9, $82, $0C, $30, $B0, $FE, $39, $33, $FF
        defb $7F, $36, $1E, $3C, $E3, $E3, $F3, $80, $C3, $08, $B0, $7C, $01, $01, $EF
        defb $F7, $36, $4E, $7C, $E7, $E1, $F3, $37, $C7, $68, $36, $3C, $C3, $3F, $FF
        defb $DF, $3E, $1C, $3C, $E0, $03, $F2, $60, $DE, $1B, $14, $FC, $9B, $0F, $FF
        defb $FF, $7E, $3D, $BD, $EF, $8B, $F0, $E3, $DE, $3B, $31, $FC, $3B, $1F, $FF
        defb $BB, $7E, $79, $9D, $EF, $99, $F3, $E7, $DE, $7B, $33, $FE, $F3, $3F, $DB
        defb $EF, $7F, $FF, $DF, $EF, $FF, $F3, $FF, $FF, $FB, $FF, $BF, $FF, $7F, $7B
        defb $FD, $DF, $FF, $FF, $FF, $FF, $F7, $FF, $FF, $FF, $FF, $BF, $FF, $FD, $EF
        defb $F7, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $DF, $F7, $BD
        defb $DF, $BE, $B7, $D5, $BF, $3D, $DE, $5E, $77, $DE, $4D, $CD, $9B, $FE, $F7
        defb $FB, $DE, $03, $95, $80, $30, $3C, $9C, $03, $14, $4D, $59, $A3, $BB, $FF
        defb $EF, $7C, $43, $21, $03, $7A, $2E, $8E, $13, $81, $80, $59, $A3, $EF, $BF
        defb $BD, $FD, $FF, $69, $FA, $FB, $DF, $FE, $F7, $DD, $B2, $1B, $BB, $FF, $ED
        defb $FF, $BF, $FF, $FF, $FF, $FF, $FF, $FD, $FF, $FF, $FF, $FF, $FE, $DA, $6F
        defb $DB, $FF, $FF, $FF, $BF, $B0, $77, $D9, $FF, $9E, $3F, $FF, $FF, $DB, $FB
        defb $FF, $7F, $FF, $FF, $1F, $30, $30, $9B, $0E, $1C, $1F, $FE, $F7, $37, $DF
        defb $EF, $F7, $FF, $FF, $0E, $34, $71, $8B, $34, $59, $9F, $F7, $BD, $FD, $F7
        defb $BF, $BF, $EF, $FF, $06, $21, $E3, $8B, $00, $D3, $DF, $ED, $EE, $CF, $BF
        defb $F6, $FE, $FD, $FF, $24, $27, $87, $83, $39, $F0, $1F, $EF, $73, $FB, $EF
        defb $DF, $FF, $FF, $DF, $60, $20, $80, $A3, $0C, $1F, $3D, $FF, $DD, $BF, $7B
        defb $FB, $7B, $FF, $FF, $19, $A6, $E7, $B3, $3F, $8E, $3F, $DB, $DF, $ED, $DF
        defb $EF, $DF, $B7, $FF, $39, $AF, $E7, $32, $7F, $18, $FF, $EF, $BB, $7F, $F7
        defb $FD, $FD, $FF, $7F, $FF, $EF, $FF, $FF, $FC, $7B, $E7, $FD, $AF, $DE, $FE
        defb $F7, $BF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $F7, $7E, $FB, $DB
        defb $BF, $FF, $FF, $FF, $FF, $F7, $FF, $FF, $FF, $FF, $EF, $FE, $DB, $EF, $FF
        defb $FF, $ED, $F8, $A2, $73, $B5, $6F, $7B, $EF, $EF, $6B, $BB, $BF, $BD, $B7
        defb $F6, $FF, $F8, $A0, $E2, $15, $4E, $41, $8A, $44, $62, $9D, $EF, $FF, $FD
        defb $DF, $F6, $F8, $1C, $E0, $12, $1E, $01, $80, $00, $04, $3F, $7E, $DB, $7F
        defb $FB, $BF, $BB, $FD, $ED, $BA, $9C, $EF, $EB, $3B, $75, $36, $DB, $FF, $DB
        defb $FF, $FD, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $F7, $FF, $B6, $FF
        defb $DD, $DF, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FD, $B7, $FF, $BF
        defb $F7, $FF, $EF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FD, $FF, $FF, $DD, $FB
        defb $FF, $77, $FF, $BF, $FF, $FF, $FF, $FF, $FF, $FF, $F7, $F6, $DB, $F7, $FE
        defb $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $B7, $FF, $FF, $FF, $FE, $FF, $BC
        defb $3F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $F8
        defb $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
