; card0_08: 2640 bytes, 15 bytes per row
card0_08:
        defb $3F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
        defb $7B, $FB, $DB, $FF, $FF, $FF, $77, $FF, $FF, $FF, $FB, $FF, $FF, $FF, $BF
        defb $7F, $FF, $7F, $FF, $FD, $B9, $FE, $BD, $DF, $7F, $FB, $FF, $77, $77, $EF
        defb $7F, $ED, $EF, $FF, $FB, $EF, $EF, $FF, $FF, $FE, $FF, $7D, $DF, $FF, $7F
        defb $7F, $BF, $BF, $DF, $EF, $7C, $FF, $FE, $EF, $F7, $F7, $DF, $FF, $EF, $DD
        defb $7F, $FE, $FF, $76, $DF, $F7, $F9, $FF, $FF, $FF, $FF, $FE, $ED, $BE, $FF
        defb $7E, $EF, $FB, $FF, $BD, $DF, $F9, $08, $78, $3F, $F7, $F7, $FF, $FB, $B7
        defb $7F, $FD, $FE, $ED, $F7, $FB, $71, $08, $48, $3D, $F7, $7F, $3F, $EF, $FD
        defb $7B, $77, $DF, $BE, $FE, $FF, $F3, $18, $C8, $FF, $FF, $FC, $8F, $FF, $DF
        defb $7F, $DF, $F7, $FC, $FF, $B7, $E0, $78, $91, $FF, $FF, $DF, $F0, $FB, $7F
        defb $7D, $FF, $7D, $DC, $CF, $FF, $41, $11, $00, $7D, $F6, $FF, $3C, $3F, $EF
        defb $7F, $EF, $F8, $98, $8F, $7D, $ED, $77, $7B, $FF, $FF, $F7, $BF, $C7, $FD
        defb $76, $FE, $E7, $8B, $0F, $FF, $FD, $77, $FF, $FF, $FB, $FF, $BF, $71, $F7
        defb $7F, $FF, $C7, $A2, $7B, $E7, $FD, $FF, $0F, $E7, $7F, $FF, $FF, $FC, $7F
        defb $7F, $7F, $FF, $B6, $D3, $E7, $FD, $FE, $0C, $E7, $FF, $DF, $FF, $EF, $3F
        defb $7B, $EE, $37, $BF, $D2, $E7, $7F, $FE, $0C, $E7, $DF, $FB, $FF, $CF, $1D
        defb $7F, $E4, $03, $80, $36, $67, $FF, $FC, $4C, $C7, $DC, $FE, $FF, $CE, $0F
        defb $7F, $C6, $03, $00, $36, $6F, $B1, $F8, $DC, $C0, $98, $FE, $67, $CC, $0F
        defb $7B, $C6, $03, $39, $F6, $67, $30, $78, $CC, $00, $98, $7C, $66, $D8, $CF
        defb $7F, $86, $C6, $19, $24, $27, $32, $71, $C0, $07, $1C, $38, $74, $D8, $C7
        defb $7F, $84, $1E, $19, $24, $26, $17, $F3, $80, $0F, $18, $18, $34, $D1, $E7
        defb $7F, $84, $3C, $48, $24, $26, $50, $E3, $81, $CF, $19, $09, $A0, $93, $97
        defb $7F, $3C, $7C, $E8, $8C, $8C, $C3, $E0, $C9, $9E, $59, $81, $A0, $10, $07
        defb $7F, $3C, $FC, $E8, $8C, $86, $03, $10, $39, $9E, $01, $93, $B2, $10, $8F
        defb $7F, $38, $08, $C9, $8D, $8E, $14, $F0, $1B, $98, $19, $11, $22, $1F, $8F
        defb $7E, $20, $00, $09, $8D, $87, $F3, $CE, $0B, $98, $49, $30, $22, $3F, $17
        defb $7E, $4C, $FC, $19, $8D, $8F, $F2, $7F, $1B, $98, $48, $70, $33, $3E, $2F
        defb $7E, $1C, $FF, $F9, $88, $C7, $DD, $9A, $1B, $9C, $C8, $CD, $E7, $3C, $6F
        defb $7C, $3C, $FF, $F9, $89, $8F, $ED, $9C, $33, $98, $C9, $3F, $F3, $3C, $DF
        defb $7F, $3C, $FF, $F9, $49, $6F, $F6, $78, $7F, $2C, $CB, $77, $F7, $39, $9F
        defb $79, $FF, $FB, $FE, $CE, $7F, $F3, $61, $FF, $27, $7F, $FF, $FF, $B9, $3F
        defb $7D, $FF, $EF, $BD, $FF, $B7, $F9, $E3, $FF, $37, $BF, $BE, $FF, $E5, $7F
        defb $7C, $FF, $BD, $F5, $ED, $E7, $F9, $C7, $FE, $37, $BF, $BF, $BF, $AF, $FF
        defb $7D, $BF, $FF, $F7, $DB, $DB, $FC, $CF, $FE, $73, $FD, $EB, $EF, $9F, $FF
        defb $7F, $7D, $EF, $BB, $9F, $DB, $FC, $9F, $F9, $73, $DF, $DE, $FE, $7F, $F9
        defb $7F, $0F, $BE, $FD, $FD, $DF, $FC, $FF, $FE, $7B, $7F, $DF, $F7, $7F, $FF
        defb $7F, $CB, $FB, $DD, $FF, $FF, $FC, $FF, $FF, $7B, $FF, $DF, $7C, $FF, $CF
        defb $7E, $FC, $FF, $7D, $FE, $FB, $7C, $FF, $FF, $FB, $FF, $DD, $DE, $FF, $7F
        defb $7E, $FC, $F7, $FD, $FF, $FF, $FC, $F7, $BB, $F3, $FB, $9F, $FC, $FD, $BF
        defb $7F, $7F, $3F, $DE, $FF, $FF, $FC, $FF, $FB, $FB, $FF, $9E, $ED, $F7, $FF
        defb $7D, $F7, $BD, $FE, $FF, $FF, $FD, $FF, $FF, $F7, $FF, $BF, $FD, $FB, $F7
        defb $7D, $DF, $77, $BC, $F7, $DE, $F9, $FF, $FF, $F7, $FF, $9F, $79, $EF, $FF
        defb $7B, $FF, $DF, $FE, $FF, $FF, $F3, $FB, $FF, $F7, $F3, $9F, $FD, $FF, $7F
        defb $7F, $BB, $DD, $DC, $FE, $FF, $F3, $FF, $DF, $F7, $CF, $DE, $DD, $DF, $FF
        defb $7B, $FF, $9F, $7D, $FF, $FF, $E7, $FF, $FD, $EF, $9F, $DF, $F9, $FF, $EF
        defb $7B, $F7, $BF, $FD, $FF, $FB, $EF, $FF, $FF, $EF, $7F, $DF, $BF, $FD, $FF
        defb $7F, $7F, $FB, $F1, $FF, $FF, $DF, $DF, $7F, $DE, $FF, $DE, $F9, $FF, $FF
        defb $7F, $FD, $9E, $FB, $FF, $FF, $9F, $FF, $FF, $9C, $FF, $EF, $ED, $FF, $BB
        defb $7B, $BF, $F7, $FB, $FF, $FF, $BF, $FB, $FF, $3D, $FB, $ED, $FC, $F7, $FF
        defb $7B, $EF, $3F, $F3, $FD, $3F, $BF, $FF, $FF, $7B, $FF, $F7, $DE, $7F, $DF
        defb $7F, $FB, $ED, $F6, $40, $9F, $7F, $BF, $DD, $7F, $EF, $F7, $7D, $FF, $FF
        defb $7D, $7E, $7F, $E7, $5F, $DF, $7F, $FF, $FD, $F7, $FF, $FB, $EF, $3D, $FF
        defb $7F, $FD, $F7, $EF, $FF, $BF, $7F, $FF, $FA, $F7, $BF, $7B, $FE, $3F, $F7
        defb $7E, $F9, $DF, $CF, $FF, $AF, $FE, $FD, $F7, $F7, $FF, $F9, $FF, $C3, $FF
        defb $7F, $C7, $FE, $1F, $FF, $BF, $3F, $FF, $FD, $E7, $F7, $F8, $FB, $F9, $F9
        defb $3C, $DF, $BE, $3F, $FF, $BF, $3F, $FF, $CF, $F7, $FF, $F3, $3F, $F6, $07
        defb $6F, $FF, $FD, $7F, $FF, $3E, $5F, $BF, $87, $D7, $BF, $F7, $9F, $FF, $FD
        defb $47, $FD, $FC, $BF, $DF, $6E, $4F, $FF, $37, $FB, $FE, $EF, $C3, $FF, $FF
        defb $71, $FF, $C3, $9E, $FE, $7E, $2F, $FF, $0F, $BB, $FF, $EF, $F8, $7F, $87
        defb $7E, $1F, $87, $DF, $FE, $F7, $8F, $FF, $4F, $B9, $F7, $EF, $FF, $00, $3F
        defb $7C, $C8, $3F, $EF, $F9, $EF, $FF, $7E, $7F, $ED, $FF, $EF, $FF, $FB, $FF
        defb $7F, $10, $FF, $EF, $FB, $FF, $FF, $FF, $FF, $DC, $FD, $F7, $FF, $FF, $FF
        defb $7F, $FF, $FF, $EF, $E7, $B7, $FF, $EF, $FF, $FE, $7F, $F7, $FF, $FF, $FF
        defb $7F, $FF, $FF, $EF, $E7, $ED, $FF, $FF, $FF, $E7, $3F, $F7, $B7, $FF, $FF
        defb $7F, $FF, $FF, $FE, $1F, $FF, $FB, $FF, $FF, $FD, $9F, $FB, $FF, $FF, $ED
        defb $7F, $FF, $DF, $EC, $7F, $9F, $FF, $FB, $FB, $FF, $C6, $79, $FF, $FF, $7F
        defb $7F, $FF, $FF, $01, $FE, $FF, $BF, $7F, $FF, $FE, $FB, $0F, $EF, $9B, $FF
        defb $7F, $27, $E8, $37, $FF, $FF, $FF, $FF, $DF, $FF, $FF, $F3, $7F, $00, $FB
        defb $7C, $90, $4A, $FF, $F9, $FD, $FE, $FF, $FE, $FF, $FD, $FD, $B8, $6E, $3F
        defb $79, $37, $7F, $FF, $FF, $FF, $EF, $FE, $FF, $FF, $07, $FE, $FE, $FF, $9F
        defb $7B, $FF, $FF, $FF, $E7, $EF, $FF, $EF, $FF, $FC, $E7, $FF, $F7, $FF, $FB
        defb $4F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $F7, $F1, $F9, $BF, $DF, $FF, $FE
        defb $5F, $FF, $FF, $FE, $FF, $FF, $FB, $FF, $FF, $C7, $FC, $ED, $FE, $FF, $F7
        defb $7F, $FE, $FF, $EF, $FF, $FF, $FF, $BF, $7F, $9F, $0F, $7F, $B8, $7F, $FF
        defb $7E, $FB, $FB, $FF, $FD, $FF, $FF, $FF, $FF, $7D, $FF, $BF, $F3, $7F, $DF
        defb $7F, $FF, $FF, $7F, $F2, $00, $7F, $FB, $FF, $67, $FC, $EA, $7D, $3B, $FF
        defb $7F, $7F, $DF, $FD, $F7, $FB, $3F, $FF, $DD, $9F, $FE, $7F, $F1, $FF, $FF
        defb $7F, $FF, $FF, $FF, $EF, $FF, $AE, $FF, $FD, $FF, $FF, $9F, $F3, $FF, $FF
        defb $7F, $BF, $FF, $EF, $9E, $7E, $7F, $EF, $FB, $FF, $FF, $E3, $8B, $C0, $1F
        defb $7F, $FF, $7F, $FF, $B9, $E0, $FF, $FE, $FF, $FF, $FF, $FD, $BB, $FF, $4F
        defb $7D, $DF, $FB, $FE, $67, $FF, $FF, $FF, $FF, $FF, $7F, $FF, $7B, $FF, $6F
        defb $7F, $FE, $FF, $FC, $CF, $FF, $FF, $BF, $FF, $FF, $FF, $FE, $77, $FF, $6F
        defb $7F, $FD, $BF, $87, $BF, $FF, $FB, $FF, $BF, $EF, $EF, $FE, $B7, $BF, $EF
        defb $7F, $DD, $9F, $BF, $7F, $FF, $FF, $F7, $FE, $FF, $FF, $FF, $67, $FB, $F7
        defb $7F, $FC, $47, $3E, $FF, $FF, $FF, $FF, $FF, $FD, $FD, $FE, $7E, $FF, $F7
        defb $7F, $FF, $FC, $FC, $FF, $BF, $EF, $DE, $F7, $FF, $FF, $FD, $E3, $EE, $F7
        defb $7F, $FE, $1E, $79, $FF, $FB, $FF, $DF, $FF, $BF, $BF, $7F, $F7, $FF, $F7
        defb $7E, $3F, $DB, $B3, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $BD, $FB
        defb $79, $A3, $BC, $E7, $FB, $FF, $7B, $9F, $FD, $F7, $F7, $FF, $FB, $F0, $FD
        defb $73, $67, $C7, $2F, $FF, $EF, $FF, $DF, $DF, $FE, $FF, $F7, $FB, $F7, $FC
        defb $76, $5F, $EF, $DF, $FF, $FF, $FF, $DF, $FB, $EF, $FF, $FF, $FB, $F9, $FE
        defb $6E, $D7, $FB, $3F, $EF, $DF, $6F, $9E, $FD, $FF, $DF, $BE, $FF, $7E, $7F
        defb $73, $27, $F9, $FF, $FD, $FF, $FF, $BF, $FF, $DE, $FF, $FF, $F7, $FF, $3F
        defb $65, $AF, $F9, $FF, $FF, $DE, $FF, $6F, $7D, $EE, $FD, $FF, $FB, $FF, $9F
        defb $6C, $DF, $FF, $FE, $FF, $DE, $FF, $4F, $FD, $FF, $FF, $EF, $FF, $FF, $CF
        defb $7B, $FE, $F7, $FF, $FD, $DE, $FF, $6F, $BD, $EE, $FF, $FF, $F6, $DF, $F3
        defb $7F, $FF, $A7, $F7, $FF, $DE, $F7, $2F, $FD, $EE, $F7, $FD, $F7, $FF, $FB
        defb $7F, $FF, $EF, $FF, $FB, $DE, $FF, $67, $FD, $DF, $FF, $BF, $F7, $FF, $FC
        defb $7F, $ED, $DF, $FF, $BF, $9E, $FF, $D7, $F9, $DD, $FF, $FF, $F7, $F7, $FE
        defb $49, $FF, $DF, $DF, $FD, $DF, $BE, $7B, $BB, $DC, $FF, $F7, $F7, $7F, $FF
        defb $7C, $FF, $DF, $FD, $FB, $DC, $FE, $CB, $FB, $DF, $EF, $FF, $F7, $FE, $F7
        defb $7F, $A3, $DF, $FF, $FB, $FE, $FD, $85, $F9, $DD, $FF, $7E, $F7, $FF, $E7
        defb $7F, $FF, $DF, $7F, $FD, $DE, $F9, $7C, $FD, $F7, $FF, $FF, $E7, $7F, $FF
        defb $7F, $FF, $DF, $FF, $FD, $DE, $DB, $FA, $43, $3E, $FB, $FF, $EF, $FB, $E7
        defb $6F, $FF, $DF, $F7, $BD, $D6, $B3, $FE, $DB, $BB, $FF, $DF, $DE, $FF, $F3
        defb $3F, $FF, $DF, $FF, $FC, $F6, $BB, $7C, $B6, $FD, $DF, $FF, $9F, $FF, $EF
        defb $77, $FF, $EF, $FF, $FF, $ED, $DD, $AD, $F5, $DF, $FE, $FF, $7F, $EF, $E7
        defb $7F, $FD, $FF, $DE, $FF, $FF, $7D, $8B, $E7, $7B, $FF, $FF, $7F, $FF, $F7
        defb $6B, $DF, $E7, $FF, $FE, $DA, $BE, $FB, $EB, $FF, $F7, $EE, $F7, $FD, $F7
        defb $7F, $FF, $F7, $FF, $FE, $FF, $9F, $76, $CE, $F7, $7F, $FE, $FF, $BF, $E1
        defb $77, $FF, $79, $FF, $BF, $B7, $5B, $77, $9F, $DF, $FF, $FD, $FF, $FF, $8F
        defb $7D, $FF, $FE, $FB, $FF, $FD, $DF, $EF, $B7, $7F, $DF, $7B, $FD, $FF, $7B
        defb $7F, $EF, $FE, $7F, $FF, $6F, $DD, $BB, $BD, $DF, $FF, $F7, $FF, $EF, $F6
        defb $7A, $FF, $FF, $7F, $F7, $BA, $DD, $DB, $B6, $FF, $FF, $CF, $EF, $FF, $C3
        defb $7E, $FE, $FF, $BF, $FF, $FF, $17, $7E, $FF, $FD, $F7, $DF, $FF, $7E, $6F
        defb $7F, $9F, $EF, $BF, $BF, $FF, $FF, $FF, $FF, $FF, $FF, $BF, $7F, $FE, $DB
        defb $4F, $FF, $FF, $9F, $FF, $FF, $FF, $FF, $FF, $EF, $FF, $7F, $FB, $F9, $F3
        defb $73, $E7, $FF, $CF, $FD, $FF, $FF, $FF, $FF, $FF, $BE, $7B, $FF, $FF, $E7
        defb $79, $7B, $FF, $E7, $FF, $DF, $FF, $F7, $DE, $FF, $FC, $FF, $DF, $DB, $AD
        defb $7F, $8E, $FF, $F7, $EF, $FD, $FF, $7F, $FF, $FF, $FD, $FF, $FF, $FF, $63
        defb $67, $E6, $FD, $F1, $FF, $BF, $EF, $FE, $FF, $DE, $FF, $FE, $FF, $FD, $DB
        defb $7C, $F9, $8F, $FE, $7F, $FF, $FF, $FF, $FB, $FF, $FE, $F7, $FF, $79, $BF
        defb $7E, $3F, $77, $FF, $1F, $FF, $7F, $7F, $FF, $FF, $DC, $FF, $FB, $6E, $E7
        defb $7B, $E7, $D7, $FF, $DD, $EF, $FF, $FB, $FF, $7B, $FD, $FF, $EB, $EB, $DB
        defb $6F, $F9, $F3, $FF, $EF, $FF, $FB, $FF, $BF, $FF, $FB, $FF, $3E, $DB, $67
        defb $7D, $DE, $7C, $FF, $FF, $FD, $FF, $DF, $FF, $FF, $FF, $FE, $7D, $F7, $FF
        defb $7D, $77, $9E, $7F, $F7, $FF, $FF, $FF, $F7, $FF, $FF, $F9, $D7, $3D, $FD
        defb $7F, $BF, $EF, $B7, $FF, $FF, $EF, $FE, $FF, $DE, $FF, $F3, $F7, $EF, $B7
        defb $77, $ED, $F7, $BF, $FF, $FF, $FF, $FF, $FF, $FC, $3F, $8E, $BD, $FB, $DF
        defb $7D, $FD, $DC, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FB, $FF, $EE, $DF, $7D
        defb $7D, $BF, $7E, $FD, $DE, $7F, $FF, $FF, $F9, $FF, $FF, $FF, $F7, $B7, $6F
        defb $5F, $EB, $DB, $FF, $00, $4E, $1A, $2C, $C9, $B1, $EE, $FF, $FD, $FD, $FB
        defb $6F, $FE, $F7, $FF, $B2, $8C, $12, $21, $C9, $83, $81, $FD, $EF, $DF, $BF
        defb $7B, $77, $BF, $FF, $B2, $CC, $96, $0D, $CA, $3B, $C1, $7F, $FF, $7E, $FD
        defb $7F, $FF, $FF, $FF, $B3, $BE, $F7, $DF, $DE, $33, $FE, $77, $FF, $0F, $F7
        defb $7F, $E6, $FF, $FF, $FF, $FF, $FF, $7F, $FF, $FF, $FB, $BF, $7F, $0F, $DF
        defb $76, $C7, $FF, $F1, $FC, $4F, $7F, $1F, $FB, $FF, $BB, $FF, $EF, $1F, $FD
        defb $77, $87, $C3, $31, $00, $0E, $7F, $02, $18, $21, $92, $3F, $C7, $70, $FF
        defb $7D, $8F, $C8, $00, $0D, $1C, $7E, $60, $60, $87, $1A, $1F, $C3, $32, $3F
        defb $7F, $CD, $C1, $07, $BC, $7C, $7E, $70, $13, $60, $02, $07, $C1, $30, $3F
        defb $6F, $CD, $CF, $8F, $38, $F8, $3E, $66, $D8, $E7, $82, $47, $C8, $33, $FF
        defb $7D, $CF, $83, $8F, $38, $20, $7E, $4C, $33, $C1, $22, $CF, $D9, $20, $FF
        defb $77, $CF, $8F, $2F, $B9, $E3, $7E, $9C, $7B, $C7, $62, $3F, $C7, $23, $FF
        defb $7E, $DF, $9E, $77, $B9, $F3, $7E, $3C, $FB, $CF, $72, $7D, $CF, $67, $FB
        defb $7F, $DF, $FF, $F7, $FF, $FF, $FE, $7F, $FF, $FF, $7F, $FF, $FF, $FF, $EE
        defb $7D, $EF, $FF, $FF, $FF, $FF, $FC, $FF, $FF, $FF, $FF, $FB, $FF, $FF, $DF
        defb $7F, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FB, $FF, $77
        defb $7B, $F7, $ED, $F7, $3F, $4F, $BF, $CF, $CE, $FB, $C9, $B5, $D9, $BD, $FF
        defb $7E, $DF, $84, $75, $64, $8E, $17, $93, $80, $62, $08, $A1, $1A, $7F, $BB
        defb $77, $FF, $10, $61, $60, $4E, $05, $D1, $82, $70, $98, $2B, $3A, $76, $EF
        defb $7D, $B7, $73, $EC, $3E, $5F, $F3, $F7, $D6, $FA, $F7, $63, $7B, $3F, $FD
        defb $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F, $FF, $FF, $FF, $FF, $FD, $93
        defb $77, $DF, $FF, $FF, $EF, $EE, $4E, $FB, $7F, $F3, $C7, $FF, $FF, $F6, $FF
        defb $3F, $7F, $FF, $FF, $E7, $EC, $06, $13, $61, $E1, $83, $FF, $ED, $B6, $FF
        defb $7B, $FF, $FF, $FF, $E3, $CC, $8C, $31, $66, $89, $3B, $FE, $FF, $DB, $B6
        defb $7F, $EF, $7F, $FF, $C0, $8C, $3C, $71, $60, $1B, $3B, $FE, $DB, $5B, $FF
        defb $7D, $FF, $F7, $BF, $CC, $84, $F0, $F0, $67, $9E, $03, $DF, $7E, $FE, $DB
        defb $77, $B7, $FF, $FF, $C8, $04, $10, $14, $61, $81, $E3, $FD, $ED, $B7, $FF
        defb $7F, $FF, $7F, $F7, $C3, $35, $9C, $F6, $43, $F1, $C7, $FE, $FB, $7D, $B7
        defb $3B, $6F, $DE, $FF, $CF, $35, $FC, $E6, $4F, $E3, $9E, $FF, $FB, $EF, $FF
        defb $7F, $FF, $F7, $FF, $FF, $7D, $FF, $FF, $7F, $CF, $3E, $F7, $B6, $FB, $6D
        defb $7F, $F7, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $ED, $DF, $FF
        defb $7B, $7F, $FF, $FF, $FF, $FE, $FF, $FF, $FF, $FF, $FE, $FF, $EF, $7D, $DF
        defb $7F, $FE, $FF, $3C, $5C, $F6, $BB, $ED, $FD, $FD, $FC, $BB, $DB, $F7, $7B
        defb $7D, $EF, $FE, $20, $1C, $44, $2B, $C8, $71, $48, $85, $4B, $76, $FF, $EF
        defb $77, $FD, $DE, $07, $38, $04, $43, $C0, $30, $00, $84, $43, $EF, $ED, $BF
        defb $7E, $DF, $7E, $6F, $3B, $27, $51, $9D, $7D, $73, $2E, $12, $ED, $BF, $F7
        defb $7F, $FB, $EF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $BF, $F6, $DF
        defb $7B, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $F6, $FF, $FB
        defb $3F, $77, $7B, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $DF, $BF, $6F
        defb $3F, $DF, $DF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $DF, $7B, $ED, $FF
        defb $1F, $FF, $FF, $EF, $FF, $FF, $FF, $FF, $DB, $7F, $FF, $FF, $FF, $FF, $FF
        defb $1F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
        defb $02, $FF, $7B, $7B, $6D, $B6, $DB, $6D, $B6, $92, $49, $24, $00, $00, $00
        defb $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
        defb $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
