"""Where everything is, and how big the board is.

Two trees, and the split is not arbitrary: map-ai-parsing/ is the pipeline -
its scans and its json are what the scripts make and remake, and nothing there
is drawn by a person. assets/quests/ is the authored side: the scene, this
tool, and art. sprites/ sits on the authored side but is GENERATED, so the one
thing you may hand it is sprites_hand/, which step 11 reads and never writes.

Every path the tool touches is named here and nowhere else. If one moves, this
is the only file that has to know.
"""
import os

import hou

HIP = hou.text.expandString("$HIP")             # assets/quests - the .hip's own dir
ROOT = os.path.dirname(os.path.dirname(HIP))    # the repo
PARSE = os.path.join(ROOT, "map-ai-parsing")

# Ours. Everything this tool writes is here, next to the scene it edits.
MANUAL = os.path.join(HIP, "manual.json")       # every hand correction
CATALOG = os.path.join(HIP, "catalog.json")     # the items, and the layers they sit in
HAND_ART = os.path.join(HIP, "sprites_hand")    # your own drawings, never overwritten
SPRITES = os.path.join(HIP, "sprites")          # GENERATED by step 11 - do not hand-edit
BUILD = os.path.join(HIP, "build_quests_hou.py")  # Apply rebuilds the scene with this

# Theirs. Read-only, plus two scripts we run: the pipeline owns all of it.
DS = os.path.join(PARSE, "ds")                  # cNN.png, the scan behind the map
WORK = os.path.join(PARSE, "work")              # the detectors and their json
ASSEMBLE = os.path.join(WORK, "09_assemble.py")     # Apply runs this
SPRITES_STEP = os.path.join(WORK, "11_sprites.py")  # Sprite... runs this

W, H = 26, 19
QUESTS = ["%02d" % i for i in range(1, 11)]

# How many of a row's leading values name the thing, the same keylen
# 09_assemble.py applies add and del with: 2 for a square, 3 for a door,
# because one square can carry both a north and a west one.
KEYLEN = {"doors": 3, "monsters": 2, "marks": 2, "special": 2}

# The layers that are not the catalogue's: each has its own row shape and
# its own meaning, and none of them is a thing you place from a list.
FIXED_LAYERS = ["doors", "openings", "monsters", "marks", "special",
                "squares", "arrows"]

SPECIALS = ["orange", "deep_red"]
LETTERS = ["A", "B", "C", "D", "E", "F", "X"]
