; board - GENERATED by assets/quests_to_asm.py, do not edit
; 
; NOT IN THE BUILD: this is 21 rooms and the game wants 22, so the
; ASSERT below fails. See the module docstring in quests_to_asm.py -
; one square, (17,13), is claimed by two room rectangles at once.
; 
rooms:
                    Room { 1,  1, 4, 3}
                    Room { 5,  1, 4, 3}
                    Room { 9,  1, 3, 5}
                    Room {14,  1, 3, 5}
                    Room {17,  1, 4, 4}
                    Room {21,  1, 4, 4}
                    Room { 1,  4, 4, 5}
                    Room { 5,  4, 4, 5}
                    Room {17,  5, 4, 4}
                    Room {21,  5, 4, 4}
                    Room {10,  7, 6, 5}
                    Room { 1, 10, 4, 4}
                    Room { 5, 10, 2, 3}
                    Room { 7, 10, 2, 3}
                    Room {21, 10, 4, 4}
                    Room { 5, 13, 4, 5}
                    Room { 9, 13, 3, 5}
                    Room {14, 13, 4, 5}
                    Room { 1, 14, 4, 4}
                    Room {18, 14, 3, 4}
                    Room {21, 14, 4, 4}
rooms_end:

    ASSERT (rooms_end - rooms) / Room == ROOM_COUNT
