;=============================================================================
; quest_data - the quests themselves, in a bank of their own
;=============================================================================
; GENERATED by assets/quests_to_asm.py from assets/quests/quests_data.json.
; Do not edit: the map half is read off the scans by map-ai-parsing and a fix
; belongs there. The text half - briefings, traps, finds, triggers - is not
; transcribed yet and comes out as empty lists; when it is written it will
; want a source file of its own beside quests_data.json, not hand edits here.
;
; Placement:  SLOT 3, PAGE 1, org $C000 - bank 1, borrowed. Nothing here is
;             ever executed and nothing here may be read unless the bank is
;             paged in. Banks 1 and 3 are the only free ones left (0 scenes,
;             2 core, 4 card text, 5 the game, 6 music) and both are
;             contended - which costs nothing here, because a quest is read
;             once, by quest.load, and never again during play.
; Depends on: MENU_STRING from game/menus/menu_structures.i, the records in
;             game/quest_structures.i, and the MT_ ids in game/globals.asm.
; Namespace:  MODULE quest_data. The campaign is the pointer table at the
;             bottom; quest.load is the only thing that should reach in.
;
; A word of warning about who may read this bank: a scene cannot. Every scene
; is PAGE 0 at this same slot, so a quest-select menu that paged this in
; would page itself out - the trap game/items.asm describes. Whatever draws a
; title from here has to live in page 5, the way game/card_text.asm does for
; the card descriptions.
;
; Every count in a header is label arithmetic and not a literal, so a row
; added by hand cannot be added and forgotten.
;
; There is no WRAP here, though the briefings will be wrapped to 28 columns
; like card_data's descriptions are. data/card_data.asm defines that constant
; and is included first, so a second one is a duplicate-label error - and
; nothing in this file needs it at assembly time anyway, because the wrapping
; happens in the exporter, before a line is ever written.
;=============================================================================

                    SLOT 3
                    PAGE 1
                    org $C000
                    MODULE quest_data

;-----------------------------------------------------------------------------
; The titles. Uppercase, like every other title in the game - the briefings
; below are mixed case, the font has both.
;
; Keep them short: a title is drawn as one MenuString on one row, so 28
; columns is the wall.
;-----------------------------------------------------------------------------
t_q01:              MENU_STRING "THE RAT AND CANDLE TAVERN"
t_q02:              MENU_STRING "JAIL BREAK"
t_q03:              MENU_STRING "MARSH OF SORROWS"
t_q04:              MENU_STRING "LOST MINE OF TYJIT SHALEAXE"
t_q05:              MENU_STRING "SUNKEN CITY OF BUUBHEALXEA"
t_q06:              MENU_STRING "TOMB OF HATE"
t_q07:              MENU_STRING "HALLS OF DOOM"
t_q08:              MENU_STRING "FORGE OF THE MOUNTAIN KING"
t_q09:              MENU_STRING "THRONE OF THE DEATH KNIGHT"
t_q10:              MENU_STRING "THE CRYPT OF PERPETUAL DARKNESS"

;-----------------------------------------------------------------------------
; The briefings - the parchment read out before the party goes down - are not
; here, because the quest notes on the bottom half of the pages have not been
; transcribed. Every Quest.BRIEF_STR below is 0, which the drawer reads as
; "no parchment" and skips.
;
; When they are written, they go here in the shape card_data uses - a line
; count, then that many MenuStrings, wrapped to WRAP columns at write time so
; nothing has to word-wrap at runtime:
;
;       b_q01:      db 3
;                   MENU_STRING "..."
;
; and the 0 in the header becomes b_q01.
;-----------------------------------------------------------------------------

;----------------------------------------------------------------------------
; Quest 1 - The Rat and Candle Tavern
; 352 squares in play, 10 doors, 27 figures, 15 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C, D
; NOTE: 3 of 15 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): stone_bench 3x1/2x1, rubble 1x2/1x1, rubble 2x1/1x1
;----------------------------------------------------------------------------
q01:                Quest {t_q01, 0, 0, 23, 1, globals.MT_ORC, OBJ_EXIT, 0, 0, (q01_doors_end-q01_doors)/Door, (q01_monsters_end-q01_monsters)/QuestMonster, (q01_furniture_end-q01_furniture)/Furniture, (q01_traps_end-q01_traps)/Trap, (q01_finds_end-q01_finds)/Find, (q01_triggers_end-q01_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q01_doors:
                    Door {5 | D_WEST, 1}             ; west wall of (5,1)
                    Door {21, 1}                     ; north wall of (21,1)
                    Door {1 | D_WEST, 3}             ; west wall of (1,3)
                    Door {25 | D_WEST, 4}            ; west wall of (25,4)
                    Door {21 | D_WEST, 5}            ; west wall of (21,5)
                    Door {25 | D_WEST, 7}            ; west wall of (25,7)
                    Door {1 | D_WEST, 8}             ; west wall of (1,8)
                    Door {8, 9}                      ; north wall of (8,9)
                    Door {12, 12}                    ; north wall of (12,12)
                    Door {14 | D_WEST, 14}           ; west wall of (14,14)
q01_doors_end:

; The roster. The square says which room the figure is in.
q01_monsters:
                    QuestMonster {globals.MT_GOBLIN, 24, 0}
                    QuestMonster {globals.MT_ORC, 1, 1}
                    QuestMonster {globals.MT_GOBLIN, 3, 1}
                    QuestMonster {globals.MT_FIMIR, 5, 1}
                    QuestMonster {globals.MT_GOBLIN, 25, 1}
                    QuestMonster {globals.MT_ORC, 2, 3}
                    QuestMonster {globals.MT_FIMIR, 8, 3}
                    QuestMonster {globals.MT_ORC, 12, 3}
                    QuestMonster {globals.MT_ORC, 13, 3}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 9, 6}
                    QuestMonster {globals.MT_ORC, 12, 8}
                    QuestMonster {globals.MT_ORC, 1, 9}
                    QuestMonster {globals.MT_ORC, 9, 9}
                    QuestMonster {globals.MT_ORC, 17, 9}
                    QuestMonster {globals.MT_ORC, 14, 10}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 16, 12}
                    QuestMonster {globals.MT_GOBLIN, 7, 13}
                    QuestMonster {globals.MT_GOBLIN, 14, 13}
                    QuestMonster {globals.MT_GOBLIN, 11, 14}
                    QuestMonster {globals.MT_GOBLIN, 9, 15}
                    QuestMonster {globals.MT_ORC, 12, 15}
                    QuestMonster {globals.MT_ORC, 13, 15}
                    QuestMonster {globals.MT_ORC, 5, 17}
                    QuestMonster {globals.MT_GOBLIN, 14, 17}
                    QuestMonster {globals.MT_GOBLIN, 0, 18}
                    QuestMonster {globals.MT_GOBLIN, 4, 18}
                    QuestMonster {globals.MT_ORC, 7, 18}
q01_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q01_furniture:
                    Furniture {FURN_TABLE, 2, 4}
                    Furniture {FURN_WEAPON_RACK, 5, 4}
                    Furniture {FURN_BED, 10, 7}
                    Furniture {FURN_TABLE, 11, 9}
                    Furniture {FURN_CHEST, 5, 10}
                    Furniture {FURN_TOMB, 15, 9}
                    Furniture {FURN_STONE_BENCH, 9, 13}
                    Furniture {FURN_ALCHEMIST, 15, 16}
                    Furniture {FURN_STAIRWAY, 23, 1}
                    Furniture {FURN_RUBBLE, 0, 0}
                    Furniture {FURN_RUBBLE, 12, 5}
                    Furniture {FURN_COLUMN, 3, 13}
                    Furniture {FURN_TRAPDOOR, 8, 0}
                    Furniture {FURN_TRAPDOOR, 6, 9}
                    Furniture {FURN_TRAPDOOR, 5, 12}
q01_furniture_end:

q01_traps:           ; the orange and deep-red squares, once the notes say what they are
q01_traps_end:

q01_finds:           ; what a search of each room turns up
q01_finds_end:

q01_triggers:        ; the story
q01_triggers_end:

;----------------------------------------------------------------------------
; Quest 2 - Jail Break
; 293 squares in play, 11 doors, 24 figures, 10 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C, D, E, X
;----------------------------------------------------------------------------
q02:                Quest {t_q02, 0, 0, 23, 1, globals.MT_ORC, OBJ_EXIT, 0, 0, (q02_doors_end-q02_doors)/Door, (q02_monsters_end-q02_monsters)/QuestMonster, (q02_furniture_end-q02_furniture)/Furniture, (q02_traps_end-q02_traps)/Trap, (q02_finds_end-q02_finds)/Find, (q02_triggers_end-q02_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q02_doors:
                    Door {18, 1}                     ; north wall of (18,1)
                    Door {21, 1}                     ; north wall of (21,1)
                    Door {25 | D_WEST, 4}            ; west wall of (25,4)
                    Door {21 | D_WEST, 5}            ; west wall of (21,5)
                    Door {25 | D_WEST, 7}            ; west wall of (25,7)
                    Door {4, 9}                      ; north wall of (4,9)
                    Door {4, 10}                     ; north wall of (4,10)
                    Door {23, 10}                    ; north wall of (23,10)
                    Door {21 | D_WEST, 11}           ; west wall of (21,11)
                    Door {12, 12}                    ; north wall of (12,12)
                    Door {22, 14}                    ; north wall of (22,14)
q02_doors_end:

; The roster. The square says which room the figure is in.
q02_monsters:
                    QuestMonster {globals.MT_ZOMBIE, 19, 1}
                    QuestMonster {globals.MT_GOBLIN, 17, 3}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 12, 5}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 13, 5}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 3, 6}
                    QuestMonster {globals.MT_GOBLIN, 19, 6}
                    QuestMonster {globals.MT_GOBLIN, 23, 6}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 4, 7}
                    QuestMonster {globals.MT_FIMIR, 1, 8}
                    QuestMonster {globals.MT_GOBLIN, 10, 8}
                    QuestMonster {globals.MT_GOBLIN, 14, 8}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 17, 9}
                    QuestMonster {globals.MT_FIMIR, 4, 10}
                    QuestMonster {globals.MT_ZOMBIE, 19, 10}
                    QuestMonster {globals.MT_GOBLIN, 10, 11}
                    QuestMonster {globals.MT_GOBLIN, 13, 11}
                    QuestMonster {globals.MT_ORC, 17, 11}
                    QuestMonster {globals.MT_ORC, 23, 11}
                    QuestMonster {globals.MT_ORC, 2, 12}
                    QuestMonster {globals.MT_ORC, 19, 12}
                    QuestMonster {globals.MT_GOBLIN, 22, 12}
                    QuestMonster {globals.MT_FIMIR, 4, 13}
                    QuestMonster {globals.MT_ORC, 23, 14}
                    QuestMonster {globals.MT_ORC, 21, 15}
q02_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q02_furniture:
                    Furniture {FURN_STAIRWAY, 23, 1}
                    Furniture {FURN_RACK, 1, 4}
                    Furniture {FURN_BED, 10, 7}
                    Furniture {FURN_WEAPON_RACK, 17, 8}
                    Furniture {FURN_TOMB, 15, 9}
                    Furniture {FURN_TABLE, 11, 9}
                    Furniture {FURN_TOMB, 1, 11}
                    Furniture {FURN_CAGE, 3, 12}
                    Furniture {FURN_STONE_BENCH, 12, 13}
                    Furniture {FURN_ALCHEMIST, 22, 16}
q02_furniture_end:

q02_traps:           ; the orange and deep-red squares, once the notes say what they are
q02_traps_end:

q02_finds:           ; what a search of each room turns up
q02_finds_end:

q02_triggers:        ; the story
q02_triggers_end:

;----------------------------------------------------------------------------
; Quest 3 - Marsh of Sorrows
; 222 squares in play, 7 doors, 21 figures, 10 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C, D, E
; NOTE: 6 of 10 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): table 1x1/3x2, rack 1x1/2x3, stairway 1x2/2x2, tomb 1x2/1x3, table 1x1/3x2, stone_bench 1x1/2x1
;----------------------------------------------------------------------------
q03:                Quest {t_q03, 0, 0, 16, 11, globals.MT_FIMIR, OBJ_EXIT, 0, 0, (q03_doors_end-q03_doors)/Door, (q03_monsters_end-q03_monsters)/QuestMonster, (q03_furniture_end-q03_furniture)/Furniture, (q03_traps_end-q03_traps)/Trap, (q03_finds_end-q03_finds)/Find, (q03_triggers_end-q03_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q03_doors:
                    Door {10, 6}                     ; north wall of (10,6)
                    Door {10, 7}                     ; north wall of (10,7)
                    Door {1 | D_WEST, 10}            ; west wall of (1,10)
                    Door {12, 12}                    ; north wall of (12,12)
                    Door {5 | D_WEST, 13}            ; west wall of (5,13)
                    Door {15, 13}                    ; north wall of (15,13)
                    Door {18 | D_WEST, 14}           ; west wall of (18,14)
q03_doors_end:

; The roster. The square says which room the figure is in.
q03_monsters:
                    QuestMonster {globals.MT_FIMIR, 21, 0}
                    QuestMonster {globals.MT_ZOMBIE, 10, 2}
                    QuestMonster {globals.MT_ZOMBIE, 10, 4}
                    QuestMonster {globals.MT_SKELETON, 10, 7}
                    QuestMonster {globals.MT_MUMMY, 13, 7}
                    QuestMonster {globals.MT_SKELETON, 0, 9}
                    QuestMonster {globals.MT_CHAOS_SORCERER, 13, 9}
                    QuestMonster {globals.MT_SKELETON, 2, 10}
                    QuestMonster {globals.MT_ZOMBIE, 3, 11}
                    QuestMonster {globals.MT_SKELETON, 10, 11}
                    QuestMonster {globals.MT_MUMMY, 13, 11}
                    QuestMonster {globals.MT_ZOMBIE, 3, 13}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 8, 13}
                    QuestMonster {globals.MT_SKELETON, 14, 13}
                    QuestMonster {globals.MT_SKELETON, 17, 13}
                    QuestMonster {globals.MT_SKELETON, 6, 14}
                    QuestMonster {globals.MT_ZOMBIE, 10, 15}
                    QuestMonster {globals.MT_SKELETON, 6, 16}
                    QuestMonster {globals.MT_FIMIR, 13, 16}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 15, 16}
                    QuestMonster {globals.MT_FIMIR, 12, 17}
q03_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q03_furniture:
                    Furniture {FURN_DREAD_SKULL, 10, 3}
                    Furniture {FURN_TABLE, 5, 3}
                    Furniture {FURN_THRONE, 14, 8}
                    Furniture {FURN_RACK, 9, 11}
                    Furniture {FURN_STAIRWAY, 16, 11}
                    Furniture {FURN_TOMB, 3, 10}
                    Furniture {FURN_TABLE, 10, 12}
                    Furniture {FURN_STONE_BENCH, 9, 13}
                    Furniture {FURN_TRAPDOOR, 8, 1}
                    Furniture {FURN_TRAPDOOR, 8, 3}
q03_furniture_end:

q03_traps:           ; the orange and deep-red squares, once the notes say what they are
q03_traps_end:

q03_finds:           ; what a search of each room turns up
q03_finds_end:

q03_triggers:        ; the story
q03_triggers_end:

;----------------------------------------------------------------------------
; Quest 4 - Lost Mine of Tyjit Shaleaxe
; 268 squares in play, 9 doors, 21 figures, 7 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C
; NOTE: 2 of 7 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): cage 2x1/1x1, tomb 1x2/1x3
;----------------------------------------------------------------------------
q04:                Quest {t_q04, 0, 0, 3, 16, globals.MT_ZOMBIE, OBJ_EXIT, 0, 0, (q04_doors_end-q04_doors)/Door, (q04_monsters_end-q04_monsters)/QuestMonster, (q04_furniture_end-q04_furniture)/Furniture, (q04_traps_end-q04_traps)/Trap, (q04_finds_end-q04_finds)/Find, (q04_triggers_end-q04_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q04_doors:
                    Door {9, 1}                      ; north wall of (9,1)
                    Door {10, 6}                     ; north wall of (10,6)
                    Door {17 | D_WEST, 6}            ; west wall of (17,6)
                    Door {21 | D_WEST, 6}            ; west wall of (21,6)
                    Door {25 | D_WEST, 6}            ; west wall of (25,6)
                    Door {10 | D_WEST, 9}            ; west wall of (10,9)
                    Door {25 | D_WEST, 10}           ; west wall of (25,10)
                    Door {1 | D_WEST, 14}            ; west wall of (1,14)
                    Door {6, 18}                     ; north wall of (6,18)
q04_doors_end:

; The roster. The square says which room the figure is in.
q04_monsters:
                    QuestMonster {globals.MT_FIMIR, 9, 2}
                    QuestMonster {globals.MT_FIMIR, 10, 4}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 12, 5}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 13, 5}
                    QuestMonster {globals.MT_SKELETON, 21, 5}
                    QuestMonster {globals.MT_SKELETON, 18, 6}
                    QuestMonster {globals.MT_ZOMBIE, 20, 6}
                    QuestMonster {globals.MT_SKELETON, 22, 6}
                    QuestMonster {globals.MT_MUMMY, 11, 7}
                    QuestMonster {globals.MT_ZOMBIE, 19, 7}
                    QuestMonster {globals.MT_SKELETON, 23, 8}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 2, 9}
                    QuestMonster {globals.MT_SKELETON, 11, 9}
                    QuestMonster {globals.MT_GARGOYLE, 14, 9}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 24, 9}
                    QuestMonster {globals.MT_MUMMY, 11, 11}
                    QuestMonster {globals.MT_ZOMBIE, 22, 12}
                    QuestMonster {globals.MT_ZOMBIE, 6, 13}
                    QuestMonster {globals.MT_SKELETON, 8, 13}
                    QuestMonster {globals.MT_SKELETON, 5, 15}
                    QuestMonster {globals.MT_SKELETON, 7, 15}
q04_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q04_furniture:
                    Furniture {FURN_THRONE, 3, 1}
                    Furniture {FURN_WEAPON_RACK, 18, 8}
                    Furniture {FURN_TOMB, 21, 11}
                    Furniture {FURN_CAGE, 23, 12}
                    Furniture {FURN_STAIRWAY, 3, 16}
                    Furniture {FURN_TOMB, 15, 8}
                    Furniture {FURN_TRAPDOOR, 2, 0}
q04_furniture_end:

q04_traps:           ; the orange and deep-red squares, once the notes say what they are
q04_traps_end:

q04_finds:           ; what a search of each room turns up
q04_finds_end:

q04_triggers:        ; the story
q04_triggers_end:

;----------------------------------------------------------------------------
; Quest 5 - Sunken City of Buubhealxea
; 308 squares in play, 11 doors, 33 figures, 15 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C, D, E, F, X
; NOTE: no stairway on the map; start square taken from the escape arrow at (9,2) - CHECK IT
; NOTE: 2 of 15 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): tomb 2x3/1x3, cage 1x2/1x1
; NOTE: 33 figures against MAX_MONSTERS 32 - the loader will refuse the last 1 if they are ever all live at once
;----------------------------------------------------------------------------
q05:                Quest {t_q05, 0, 0, 9, 2, globals.MT_FIMIR, OBJ_EXIT, 0, 0, (q05_doors_end-q05_doors)/Door, (q05_monsters_end-q05_monsters)/QuestMonster, (q05_furniture_end-q05_furniture)/Furniture, (q05_traps_end-q05_traps)/Trap, (q05_finds_end-q05_finds)/Find, (q05_triggers_end-q05_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q05_doors:
                    Door {10, 1}                     ; north wall of (10,1)
                    Door {15, 1}                     ; north wall of (15,1)
                    Door {17 | D_WEST, 5}            ; west wall of (17,5)
                    Door {21 | D_WEST, 6}            ; west wall of (21,6)
                    Door {7, 9}                      ; north wall of (7,9)
                    Door {16 | D_WEST, 9}            ; west wall of (16,9)
                    Door {25 | D_WEST, 11}           ; west wall of (25,11)
                    Door {1 | D_WEST, 12}            ; west wall of (1,12)
                    Door {21 | D_WEST, 12}           ; west wall of (21,12)
                    Door {23, 14}                    ; north wall of (23,14)
                    Door {1 | D_WEST, 15}            ; west wall of (1,15)
q05_doors_end:

; The roster. The square says which room the figure is in.
q05_monsters:
                    QuestMonster {globals.MT_GOBLIN, 11, 1}
                    QuestMonster {globals.MT_ORC, 16, 1}
                    QuestMonster {globals.MT_GOBLIN, 10, 2}
                    QuestMonster {globals.MT_FIMIR, 15, 2}
                    QuestMonster {globals.MT_ORC, 14, 4}
                    QuestMonster {globals.MT_FIMIR, 12, 5}
                    QuestMonster {globals.MT_FIMIR, 13, 5}
                    QuestMonster {globals.MT_ZOMBIE, 19, 5}
                    QuestMonster {globals.MT_SKELETON, 21, 5}
                    QuestMonster {globals.MT_SKELETON, 23, 5}
                    QuestMonster {globals.MT_FIMIR, 7, 6}
                    QuestMonster {globals.MT_ZOMBIE, 13, 7}
                    QuestMonster {globals.MT_ZOMBIE, 18, 7}
                    QuestMonster {globals.MT_SKELETON, 22, 7}
                    QuestMonster {globals.MT_ORC, 12, 8}
                    QuestMonster {globals.MT_ORC, 15, 8}
                    QuestMonster {globals.MT_ZOMBIE, 24, 8}
                    QuestMonster {globals.MT_GOBLIN, 11, 9}
                    QuestMonster {globals.MT_ORC, 12, 10}
                    QuestMonster {globals.MT_ORC, 13, 10}
                    QuestMonster {globals.MT_GOBLIN, 4, 11}
                    QuestMonster {globals.MT_ZOMBIE, 15, 11}
                    QuestMonster {globals.MT_GOBLIN, 23, 11}
                    QuestMonster {globals.MT_FIMIR, 3, 12}
                    QuestMonster {globals.MT_GOBLIN, 22, 12}
                    QuestMonster {globals.MT_GOBLIN, 2, 13}
                    QuestMonster {globals.MT_ORC, 2, 14}
                    QuestMonster {globals.MT_GOBLIN, 3, 15}
                    QuestMonster {globals.MT_FIMIR, 21, 15}
                    QuestMonster {globals.MT_GOBLIN, 1, 16}
                    QuestMonster {globals.MT_ORC, 3, 17}
                    QuestMonster {globals.MT_FIMIR, 23, 17}
                    QuestMonster {globals.MT_FIMIR, 6, 18}
q05_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q05_furniture:
                    Furniture {FURN_TOMB, 21, 2}
                    Furniture {FURN_ALCHEMIST | (DIR_EAST << F_ORIENT_SHIFT), 9, 3}
                    Furniture {FURN_CAGE, 5, 4}
                    Furniture {FURN_TOMB, 5, 6}
                    Furniture {FURN_COLUMN, 17, 6}
                    Furniture {FURN_DREAD_SKULL, 7, 7}
                    Furniture {FURN_CAGE, 10, 8}
                    Furniture {FURN_BED, 2, 10}
                    Furniture {FURN_LOOM, 17, 10}
                    Furniture {FURN_STONE_BENCH, 12, 13}
                    Furniture {FURN_TRAPDOOR, 24, 0}
                    Furniture {FURN_TRAPDOOR, 8, 5}
                    Furniture {FURN_TRAPDOOR, 21, 8}
                    Furniture {FURN_TRAPDOOR, 4, 16}
                    Furniture {FURN_TRAPDOOR, 21, 17}
q05_furniture_end:

q05_traps:           ; the orange and deep-red squares, once the notes say what they are
q05_traps_end:

q05_finds:           ; what a search of each room turns up
q05_finds_end:

q05_triggers:        ; the story
q05_triggers_end:

;----------------------------------------------------------------------------
; Quest 6 - Tomb of Hate
; 266 squares in play, 9 doors, 27 figures, 13 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C
; NOTE: 2 of 13 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): stone_bench 3x1/2x1, table 1x1/3x2
;----------------------------------------------------------------------------
q06:                Quest {t_q06, 0, 0, 16, 16, globals.MT_MUMMY, OBJ_EXIT, 0, 0, (q06_doors_end-q06_doors)/Door, (q06_monsters_end-q06_monsters)/QuestMonster, (q06_furniture_end-q06_furniture)/Furniture, (q06_traps_end-q06_traps)/Trap, (q06_finds_end-q06_finds)/Find, (q06_triggers_end-q06_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q06_doors:
                    Door {3, 1}                      ; north wall of (3,1)
                    Door {3, 4}                      ; north wall of (3,4)
                    Door {1 | D_WEST, 8}             ; west wall of (1,8)
                    Door {10 | D_WEST, 9}            ; west wall of (10,9)
                    Door {14, 13}                    ; north wall of (14,13)
                    Door {21 | D_WEST, 13}           ; west wall of (21,13)
                    Door {19, 14}                    ; north wall of (19,14)
                    Door {25 | D_WEST, 16}           ; west wall of (25,16)
                    Door {19, 18}                    ; north wall of (19,18)
q06_doors_end:

; The roster. The square says which room the figure is in.
q06_monsters:
                    QuestMonster {globals.MT_SKELETON, 12, 0}
                    QuestMonster {globals.MT_ZOMBIE, 24, 0}
                    QuestMonster {globals.MT_SKELETON, 2, 1}
                    QuestMonster {globals.MT_SKELETON, 13, 1}
                    QuestMonster {globals.MT_SKELETON, 4, 2}
                    QuestMonster {globals.MT_SKELETON, 2, 3}
                    QuestMonster {globals.MT_SKELETON, 4, 4}
                    QuestMonster {globals.MT_ZOMBIE, 2, 5}
                    QuestMonster {globals.MT_ZOMBIE, 3, 7}
                    QuestMonster {globals.MT_SKELETON, 10, 7}
                    QuestMonster {globals.MT_SKELETON, 15, 7}
                    QuestMonster {globals.MT_MUMMY, 14, 9}
                    QuestMonster {globals.MT_SKELETON, 10, 11}
                    QuestMonster {globals.MT_ZOMBIE, 15, 11}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 22, 11}
                    QuestMonster {globals.MT_MUMMY, 19, 12}
                    QuestMonster {globals.MT_ZOMBIE, 12, 13}
                    QuestMonster {globals.MT_SKELETON, 18, 13}
                    QuestMonster {globals.MT_SKELETON, 20, 13}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 23, 13}
                    QuestMonster {globals.MT_ZOMBIE, 13, 14}
                    QuestMonster {globals.MT_SKELETON, 22, 14}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 20, 15}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 18, 16}
                    QuestMonster {globals.MT_SKELETON, 12, 17}
                    QuestMonster {globals.MT_SKELETON, 23, 17}
                    QuestMonster {globals.MT_SKELETON, 13, 18}
q06_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q06_furniture:
                    Furniture {FURN_TOMB, 1, 1}
                    Furniture {FURN_TOMB, 1, 4}
                    Furniture {FURN_STONE_BENCH, 2, 8}
                    Furniture {FURN_TOMB_SWORD, 12, 8}
                    Furniture {FURN_RACK, 23, 10}
                    Furniture {FURN_ALTAR, 18, 10}
                    Furniture {FURN_CAGE, 21, 11}
                    Furniture {FURN_ALCHEMIST, 15, 13}
                    Furniture {FURN_BOOKCASE, 21, 14}
                    Furniture {FURN_STAIRWAY, 16, 16}
                    Furniture {FURN_TABLE, 14, 17}
                    Furniture {FURN_RUBBLE, 9, 8}
                    Furniture {FURN_TRAPDOOR, 14, 11}
q06_furniture_end:

q06_traps:           ; the orange and deep-red squares, once the notes say what they are
q06_traps_end:

q06_finds:           ; what a search of each room turns up
q06_finds_end:

q06_triggers:        ; the story
q06_triggers_end:

;----------------------------------------------------------------------------
; Quest 7 - Halls of Doom
; 299 squares in play, 16 doors, 33 figures, 10 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C, D
; NOTE: 4 of 10 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): altar 1x1/3x2, stone_bench 3x1/2x1, column 2x1/1x3, column 1x1/1x3
; NOTE: 33 figures against MAX_MONSTERS 32 - the loader will refuse the last 1 if they are ever all live at once
;----------------------------------------------------------------------------
q07:                Quest {t_q07, 0, 0, 21, 16, globals.MT_CHAOS_WARRIOR, OBJ_EXIT, 0, 0, (q07_doors_end-q07_doors)/Door, (q07_monsters_end-q07_monsters)/QuestMonster, (q07_furniture_end-q07_furniture)/Furniture, (q07_traps_end-q07_traps)/Trap, (q07_finds_end-q07_finds)/Find, (q07_triggers_end-q07_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q07_doors:
                    Door {9, 1}                      ; north wall of (9,1)
                    Door {1 | D_WEST, 4}             ; west wall of (1,4)
                    Door {9 | D_WEST, 4}             ; west wall of (9,4)
                    Door {5 | D_WEST, 5}             ; west wall of (5,5)
                    Door {21 | D_WEST, 5}            ; west wall of (21,5)
                    Door {17 | D_WEST, 6}            ; west wall of (17,6)
                    Door {7, 9}                      ; north wall of (7,9)
                    Door {24, 9}                     ; north wall of (24,9)
                    Door {5, 10}                     ; north wall of (5,10)
                    Door {20, 10}                    ; north wall of (20,10)
                    Door {17, 13}                    ; north wall of (17,13)
                    Door {12 | D_WEST, 15}           ; west wall of (12,15)
                    Door {25 | D_WEST, 15}           ; west wall of (25,15)
                    Door {1 | D_WEST, 16}            ; west wall of (1,16)
                    Door {3, 18}                     ; north wall of (3,18)
                    Door {15, 18}                    ; north wall of (15,18)
q07_doors_end:

; The roster. The square says which room the figure is in.
q07_monsters:
                    QuestMonster {globals.MT_ZOMBIE, 0, 0}
                    QuestMonster {globals.MT_FIMIR, 12, 0}
                    QuestMonster {globals.MT_ZOMBIE, 23, 0}
                    QuestMonster {globals.MT_FIMIR, 11, 2}
                    QuestMonster {globals.MT_ORC, 2, 4}
                    QuestMonster {globals.MT_ORC, 4, 4}
                    QuestMonster {globals.MT_FIMIR, 10, 4}
                    QuestMonster {globals.MT_ORC, 3, 6}
                    QuestMonster {globals.MT_GOBLIN, 7, 6}
                    QuestMonster {globals.MT_GOBLIN, 5, 7}
                    QuestMonster {globals.MT_ORC, 6, 7}
                    QuestMonster {globals.MT_GOBLIN, 21, 7}
                    QuestMonster {globals.MT_GOBLIN, 24, 7}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 25, 9}
                    QuestMonster {globals.MT_MUMMY, 6, 11}
                    QuestMonster {globals.MT_GOBLIN, 19, 11}
                    QuestMonster {globals.MT_MUMMY, 5, 12}
                    QuestMonster {globals.MT_FIMIR, 12, 13}
                    QuestMonster {globals.MT_FIMIR, 13, 13}
                    QuestMonster {globals.MT_GOBLIN, 1, 14}
                    QuestMonster {globals.MT_ORC, 12, 14}
                    QuestMonster {globals.MT_ORC, 13, 14}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 15, 14}
                    QuestMonster {globals.MT_ORC, 4, 15}
                    QuestMonster {globals.MT_SKELETON, 12, 15}
                    QuestMonster {globals.MT_SKELETON, 13, 15}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 16, 15}
                    QuestMonster {globals.MT_ORC, 2, 16}
                    QuestMonster {globals.MT_SKELETON, 12, 16}
                    QuestMonster {globals.MT_SKELETON, 13, 16}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 6, 18}
                    QuestMonster {globals.MT_ZOMBIE, 18, 18}
                    QuestMonster {globals.MT_ZOMBIE, 21, 18}
q07_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q07_furniture:
                    Furniture {FURN_STONE_BENCH, 12, 5}
                    Furniture {FURN_TABLE, 22, 5}
                    Furniture {FURN_RACK, 1, 6}
                    Furniture {FURN_BED, 18, 8}
                    Furniture {FURN_ALTAR, 1, 9}
                    Furniture {FURN_STONE_BENCH, 18, 13}
                    Furniture {FURN_BED, 2, 14}
                    Furniture {FURN_COLUMN, 11, 15}
                    Furniture {FURN_STAIRWAY, 21, 16}
                    Furniture {FURN_COLUMN, 9, 10}
q07_furniture_end:

q07_traps:           ; the orange and deep-red squares, once the notes say what they are
q07_traps_end:

q07_finds:           ; what a search of each room turns up
q07_finds_end:

q07_triggers:        ; the story
q07_triggers_end:

;----------------------------------------------------------------------------
; Quest 8 - Forge of the Mountain King
; 284 squares in play, 14 doors, 31 figures, 18 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C, D, E, F
; NOTE: no stairway and no escape arrow - start square left at (0,0)
; NOTE: 4 of 18 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): bed 1x1/3x1, cage 3x1/1x1, tomb_sword 1x1/2x3, tomb 2x3/1x3
;----------------------------------------------------------------------------
q08:                Quest {t_q08, 0, 0, 0, 0, globals.MT_MUMMY, OBJ_EXIT, 0, 0, (q08_doors_end-q08_doors)/Door, (q08_monsters_end-q08_monsters)/QuestMonster, (q08_furniture_end-q08_furniture)/Furniture, (q08_traps_end-q08_traps)/Trap, (q08_finds_end-q08_finds)/Find, (q08_triggers_end-q08_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q08_doors:
                    Door {9, 1}                      ; north wall of (9,1)
                    Door {12, 7}                     ; north wall of (12,7)
                    Door {4, 9}                      ; north wall of (4,9)
                    Door {2, 10}                     ; north wall of (2,10)
                    Door {9 | D_WEST, 10}            ; west wall of (9,10)
                    Door {10 | D_WEST, 10}           ; west wall of (10,10)
                    Door {16 | D_WEST, 10}           ; west wall of (16,10)
                    Door {17 | D_WEST, 10}           ; west wall of (17,10)
                    Door {1 | D_WEST, 12}            ; west wall of (1,12)
                    Door {25 | D_WEST, 12}           ; west wall of (25,12)
                    Door {5 | D_WEST, 13}            ; west wall of (5,13)
                    Door {7, 13}                     ; north wall of (7,13)
                    Door {3, 14}                     ; north wall of (3,14)
                    Door {18, 14}                    ; north wall of (18,14)
q08_doors_end:

; The roster. The square says which room the figure is in.
q08_monsters:
                    QuestMonster {globals.MT_GOBLIN, 9, 0}
                    QuestMonster {globals.MT_GOBLIN, 0, 2}
                    QuestMonster {globals.MT_FIMIR, 2, 6}
                    QuestMonster {globals.MT_ORC, 4, 6}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 9, 6}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 16, 6}
                    QuestMonster {globals.MT_ZOMBIE, 13, 7}
                    QuestMonster {globals.MT_ORC, 3, 8}
                    QuestMonster {globals.MT_SKELETON, 12, 8}
                    QuestMonster {globals.MT_MUMMY, 14, 8}
                    QuestMonster {globals.MT_SKELETON, 11, 9}
                    QuestMonster {globals.MT_SKELETON, 13, 9}
                    QuestMonster {globals.MT_ZOMBIE, 4, 10}
                    QuestMonster {globals.MT_ZOMBIE, 13, 10}
                    QuestMonster {globals.MT_SKELETON, 18, 10}
                    QuestMonster {globals.MT_ORC, 2, 11}
                    QuestMonster {globals.MT_SKELETON, 8, 11}
                    QuestMonster {globals.MT_SKELETON, 21, 11}
                    QuestMonster {globals.MT_ORC, 3, 12}
                    QuestMonster {globals.MT_SKELETON, 17, 12}
                    QuestMonster {globals.MT_SKELETON, 23, 12}
                    QuestMonster {globals.MT_ORC, 2, 13}
                    QuestMonster {globals.MT_SKELETON, 19, 13}
                    QuestMonster {globals.MT_SKELETON, 23, 13}
                    QuestMonster {globals.MT_ORC, 7, 14}
                    QuestMonster {globals.MT_FIMIR, 4, 15}
                    QuestMonster {globals.MT_GOBLIN, 6, 15}
                    QuestMonster {globals.MT_MUMMY, 19, 15}
                    QuestMonster {globals.MT_FIMIR, 3, 16}
                    QuestMonster {globals.MT_ORC, 5, 16}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 1, 18}
q08_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q08_furniture:
                    Furniture {FURN_TABLE, 1, 4}
                    Furniture {FURN_TOMB, 10, 7}
                    Furniture {FURN_MACHINE, 15, 7}
                    Furniture {FURN_BED, 25, 10}
                    Furniture {FURN_ALCHEMIST | (DIR_EAST << F_ORIENT_SHIFT), 19, 10}
                    Furniture {FURN_FORGE, 22, 10}
                    Furniture {FURN_CAGE, 10, 11}
                    Furniture {FURN_TOMB_SWORD, 5, 13}
                    Furniture {FURN_TOMB, 14, 15}
                    Furniture {FURN_ALTAR, 18, 16}
                    Furniture {FURN_BED, 6, 17}
                    Furniture {FURN_LOOM, 1, 15}
                    Furniture {FURN_BARREL, 20, 13}
                    Furniture {FURN_RUBBLE, 16, 11}
                    Furniture {FURN_TRAPDOOR, 15, 0}
                    Furniture {FURN_TRAPDOOR, 14, 5}
                    Furniture {FURN_TRAPDOOR, 21, 13}
                    Furniture {FURN_TRAPDOOR, 17, 15}
q08_furniture_end:

q08_traps:           ; the orange and deep-red squares, once the notes say what they are
q08_traps_end:

q08_finds:           ; what a search of each room turns up
q08_finds_end:

q08_triggers:        ; the story
q08_triggers_end:

;----------------------------------------------------------------------------
; Quest 9 - Throne of the Death Knight
; 297 squares in play, 9 doors, 33 figures, 15 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C
; NOTE: 1 of 15 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): table 1x1/3x2
; NOTE: 33 figures against MAX_MONSTERS 32 - the loader will refuse the last 1 if they are ever all live at once
;----------------------------------------------------------------------------
q09:                Quest {t_q09, 0, 0, 3, 10, globals.MT_CHAOS_WARRIOR, OBJ_EXIT, 0, 0, (q09_doors_end-q09_doors)/Door, (q09_monsters_end-q09_monsters)/QuestMonster, (q09_furniture_end-q09_furniture)/Furniture, (q09_traps_end-q09_traps)/Trap, (q09_finds_end-q09_finds)/Find, (q09_triggers_end-q09_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q09_doors:
                    Door {7, 4}                      ; north wall of (7,4)
                    Door {24, 5}                     ; north wall of (24,5)
                    Door {5 | D_WEST, 6}             ; west wall of (5,6)
                    Door {21, 9}                     ; north wall of (21,9)
                    Door {5, 10}                     ; north wall of (5,10)
                    Door {20, 10}                    ; north wall of (20,10)
                    Door {1 | D_WEST, 13}            ; west wall of (1,13)
                    Door {5, 13}                     ; north wall of (5,13)
                    Door {18 | D_WEST, 13}           ; west wall of (18,13)
q09_doors_end:

; The roster. The square says which room the figure is in.
q09_monsters:
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 4, 0}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 20, 0}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 6, 2}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 8, 2}
                    QuestMonster {globals.MT_SKELETON, 12, 2}
                    QuestMonster {globals.MT_SKELETON, 13, 2}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 23, 2}
                    QuestMonster {globals.MT_SKELETON, 12, 3}
                    QuestMonster {globals.MT_SKELETON, 13, 3}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 4, 4}
                    QuestMonster {globals.MT_SKELETON, 12, 4}
                    QuestMonster {globals.MT_SKELETON, 13, 4}
                    QuestMonster {globals.MT_MUMMY, 5, 5}
                    QuestMonster {globals.MT_CHAOS_SORCERER, 2, 6}
                    QuestMonster {globals.MT_ZOMBIE, 16, 6}
                    QuestMonster {globals.MT_ORC, 23, 6}
                    QuestMonster {globals.MT_MUMMY, 5, 7}
                    QuestMonster {globals.MT_ORC, 21, 7}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 3, 8}
                    QuestMonster {globals.MT_ORC, 19, 11}
                    QuestMonster {globals.MT_ZOMBIE, 9, 12}
                    QuestMonster {globals.MT_GOBLIN, 20, 12}
                    QuestMonster {globals.MT_ORC, 15, 13}
                    QuestMonster {globals.MT_GOBLIN, 19, 13}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 25, 13}
                    QuestMonster {globals.MT_MUMMY, 5, 14}
                    QuestMonster {globals.MT_ORC, 17, 14}
                    QuestMonster {globals.MT_MUMMY, 8, 15}
                    QuestMonster {globals.MT_GARGOYLE, 16, 15}
                    QuestMonster {globals.MT_ZOMBIE, 6, 16}
                    QuestMonster {globals.MT_ORC, 17, 16}
                    QuestMonster {globals.MT_ZOMBIE, 7, 17}
                    QuestMonster {globals.MT_ORC, 15, 17}
q09_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q09_furniture:
                    Furniture {FURN_TABLE, 7, 1}
                    Furniture {FURN_ALCHEMIST | (DIR_EAST << F_ORIENT_SHIFT), 21, 1}
                    Furniture {FURN_BED, 21, 5}
                    Furniture {FURN_CAGE, 1, 6}
                    Furniture {FURN_STAIRWAY, 3, 10}
                    Furniture {FURN_LOOM, 17, 10}
                    Furniture {FURN_STONE_BENCH, 12, 13}
                    Furniture {FURN_ALTAR, 6, 13}
                    Furniture {FURN_TOMB, 14, 14}
                    Furniture {FURN_STONE_BENCH, 12, 17}
                    Furniture {FURN_RUBBLE, 0, 10}
                    Furniture {FURN_TRAPDOOR, 8, 6}
                    Furniture {FURN_TRAPDOOR, 0, 6}
                    Furniture {FURN_TRAPDOOR, 5, 18}
                    Furniture {FURN_TRAPDOOR, 17, 18}
q09_furniture_end:

q09_traps:           ; the orange and deep-red squares, once the notes say what they are
q09_traps_end:

q09_finds:           ; what a search of each room turns up
q09_finds_end:

q09_triggers:        ; the story
q09_triggers_end:

;----------------------------------------------------------------------------
; Quest 10 - The Crypt of Perpetual Darkness
; 328 squares in play, 13 doors, 29 figures, 13 pieces of furniture.
; Marked on the map, and waiting on the notes: A, B, C, D, E, X
; NOTE: no stairway on the map; start square taken from the escape arrow at (16,8) - CHECK IT
; NOTE: the title is 31 columns and the row is 28 - it will be drawn cut off
; NOTE: 3 of 13 furniture footprints are neither the type's shape nor its transpose, so they are emitted unturned (they are ink bounding boxes, not tile sizes): stone_bench 1x1/2x1, bed 1x1/3x1, bed 1x1/3x1
;----------------------------------------------------------------------------
q10:                Quest {t_q10, 0, 0, 16, 8, globals.MT_CHAOS_WARRIOR, OBJ_EXIT, 0, 0, (q10_doors_end-q10_doors)/Door, (q10_monsters_end-q10_monsters)/QuestMonster, (q10_furniture_end-q10_furniture)/Furniture, (q10_traps_end-q10_traps)/Trap, (q10_finds_end-q10_finds)/Find, (q10_triggers_end-q10_triggers)/Trigger}

; Doors. Always the north or the west wall of the square named.
q10_doors:
                    Door {10, 1}                     ; north wall of (10,1)
                    Door {25 | D_WEST, 2}            ; west wall of (25,2)
                    Door {17 | D_WEST, 7}            ; west wall of (17,7)
                    Door {2, 10}                     ; north wall of (2,10)
                    Door {6, 10}                     ; north wall of (6,10)
                    Door {7 | D_WEST, 11}            ; west wall of (7,11)
                    Door {9 | D_WEST, 11}            ; west wall of (9,11)
                    Door {10 | D_WEST, 11}           ; west wall of (10,11)
                    Door {11, 12}                    ; north wall of (11,12)
                    Door {1 | D_WEST, 16}            ; west wall of (1,16)
                    Door {12 | D_WEST, 17}           ; west wall of (12,17)
                    Door {9, 18}                     ; north wall of (9,18)
                    Door {16, 18}                    ; north wall of (16,18)
q10_doors_end:

; The roster. The square says which room the figure is in.
q10_monsters:
                    QuestMonster {globals.MT_MUMMY, 1, 0}
                    QuestMonster {globals.MT_MUMMY, 8, 0}
                    QuestMonster {globals.MT_GARGOYLE, 4, 3}
                    QuestMonster {globals.MT_GOBLIN, 17, 6}
                    QuestMonster {globals.MT_SKELETON, 13, 7}
                    QuestMonster {globals.MT_FIMIR, 20, 7}
                    QuestMonster {globals.MT_SKELETON, 15, 8}
                    QuestMonster {globals.MT_GOBLIN, 18, 8}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 0, 9}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 9, 9}
                    QuestMonster {globals.MT_ZOMBIE, 11, 9}
                    QuestMonster {globals.MT_ORC, 1, 10}
                    QuestMonster {globals.MT_ZOMBIE, 4, 10}
                    QuestMonster {globals.MT_MUMMY, 12, 10}
                    QuestMonster {globals.MT_SKELETON, 13, 10}
                    QuestMonster {globals.MT_ZOMBIE, 15, 10}
                    QuestMonster {globals.MT_ORC, 3, 11}
                    QuestMonster {globals.MT_ORC, 5, 11}
                    QuestMonster {globals.MT_SKELETON, 11, 11}
                    QuestMonster {globals.MT_MUMMY, 14, 11}
                    QuestMonster {globals.MT_ORC, 1, 12}
                    QuestMonster {globals.MT_GOBLIN, 7, 12}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 12, 14}
                    QuestMonster {globals.MT_FIMIR, 14, 14}
                    QuestMonster {globals.MT_GOBLIN, 3, 15}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 10, 15}
                    QuestMonster {globals.MT_CHAOS_WARRIOR, 13, 15}
                    QuestMonster {globals.MT_FIMIR, 15, 16}
                    QuestMonster {globals.MT_FIMIR, 17, 17}
q10_monsters_end:

; Furniture. X,Y is the top-left square it covers once turned.
q10_furniture:
                    Furniture {FURN_STONE_BENCH, 12, 1}
                    Furniture {FURN_WEAPON_RACK, 17, 5}
                    Furniture {FURN_BOOKCASE | (DIR_EAST << F_ORIENT_SHIFT), 9, 5}
                    Furniture {FURN_TOMB_SWORD | (DIR_EAST << F_ORIENT_SHIFT), 10, 7}
                    Furniture {FURN_STONE_BENCH, 12, 9}
                    Furniture {FURN_BED, 15, 9}
                    Furniture {FURN_BED, 24, 9}
                    Furniture {FURN_TABLE, 15, 13}
                    Furniture {FURN_ALTAR, 9, 13}
                    Furniture {FURN_BED, 2, 17}
                    Furniture {FURN_RUBBLE, 23, 0}
                    Furniture {FURN_TRAPDOOR, 9, 0}
                    Furniture {FURN_LAIR_ART, 0, 0}
q10_furniture_end:

q10_traps:           ; the orange and deep-red squares, once the notes say what they are
q10_traps_end:

q10_finds:           ; what a search of each room turns up
q10_finds_end:

q10_triggers:        ; the story
q10_triggers_end:

;-----------------------------------------------------------------------------
; The campaign - the order they are played in, and the only thing outside
; this file that has to know how many there are. QUEST_COUNT counts the
; table, so adding a quest is one line here and nothing else.
;-----------------------------------------------------------------------------
quests:
                    dw q01, q02, q03, q04, q05
                    dw q06, q07, q08, q09, q10
quests_end:

QUEST_COUNT         equ (quests_end - quests) / 2

; Ten in this release. Not a limit - the table is what says how many - but a
; quest that goes missing from it, or a title written without a body behind
; it, stops the build here rather than showing up as a short campaign menu.
    ASSERT QUEST_COUNT == 10

BYTES               equ quests_end - t_q01

                    ASSERT BYTES < $4000        ; it has to fit the bank
                    DISPLAY "quests: ", /D, BYTES, " bytes in bank 1"

                    ENDMODULE
